import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

const adminOnly = [requireSupabaseAuth] as const;
async function assertAdmin(context: any){if (!context) throw new Error("Unauthorized"); const {data,error}=await context.supabase.rpc("is_super_admin");if(error||data!==true)throw new Error("Forbidden");}
export const getAdminDashboard=createServerFn({method:"GET"}).middleware(adminOnly).handler(async({context})=>{await assertAdmin(context);const [sellers,apps,products,orders,reviews,settlements,homepage]=await Promise.all([context.supabase.from("sellers").select("id,legal_name,account_status,commission_rate,created_at").order("created_at",{ascending:false}).limit(50),context.supabase.from("seller_applications").select("id,first_name,last_name,email,proposed_store_name,status,created_at").order("created_at",{ascending:false}).limit(50),context.supabase.from("products").select("id,slug,name,base_price,status,publication_status,moderation_status,seller_id,created_at").order("created_at",{ascending:false}).limit(80),context.supabase.from("orders").select("id,order_number,grand_total,status,created_at,first_name,last_name").order("created_at",{ascending:false}).limit(80),context.supabase.from("reviews").select("id,product_id,rating,body,moderation_status,created_at").order("created_at",{ascending:false}).limit(50),context.supabase.from("seller_settlements").select("id,seller_id,amount,status,created_at,payment_reference").order("created_at",{ascending:false}).limit(50),context.supabase.from("homepage_sections").select("id,section_key,kind,title,enabled,sort_order").order("sort_order")]);return {sellers:sellers.data??[],applications:apps.data??[],products:products.data??[],orders:orders.data??[],reviews:reviews.data??[],settlements:settlements.data??[],homepage:homepage.data??[]};});

export const approveSellerApplication=createServerFn({method:"POST"}).middleware(adminOnly).inputValidator(data=>z.object({applicationId:z.string().uuid()}).parse(data)).handler(async({data,context})=>{await assertAdmin(context);const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const {data:app,error}=await supabaseAdmin.from("seller_applications").select("*").eq("id",data.applicationId).maybeSingle();if(error||!app)throw new Error("Application not found.");if(app.status!=="pending")throw new Error("Application is not pending.");const {data:seller,error:sellerError}=await supabaseAdmin.from("sellers").insert({owner_id:app.applicant_id,legal_name:app.proposed_store_name,first_name:app.first_name,last_name:app.last_name,phone:app.phone,email:app.email,status:"active",account_status:"active",commission_rate:.1,approved_at:new Date().toISOString()}).select("id").single();if(sellerError||!seller)throw new Error(sellerError?.message??"Could not create seller.");const slug=app.proposed_store_name.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")+"-"+seller.id.slice(0,6);const {error:storeError}=await supabaseAdmin.from("stores").insert({seller_id:seller.id,name:app.proposed_store_name,slug,status:"active",verification_status:"unverified",description:app.business_description});if(storeError)throw new Error(storeError.message);await supabaseAdmin.from("user_roles").upsert({user_id:app.applicant_id,role:"seller_owner"},{onConflict:"user_id,role"});const {error:updateError}=await supabaseAdmin.from("seller_applications").update({status:"approved",reviewed_at:new Date().toISOString(),reviewed_by:context.userId,seller_id:seller.id}).eq("id",app.id);if(updateError)throw new Error(updateError.message);await supabaseAdmin.from("audit_logs").insert({actor_id:context.userId,action:"seller_application_approved",resource:"seller_application",resource_id:app.id,metadata:{seller_id:seller.id}});return {sellerId:seller.id};});

export const moderateProduct=createServerFn({method:"POST"}).middleware(adminOnly).inputValidator(data=>z.object({productId:z.string().uuid(),decision:z.enum(["approve","reject","hide"])}).parse(data)).handler(async({data,context})=>{await assertAdmin(context);const update=data.decision==="approve"?{moderation_status:"approved",publication_status:"published",visibility:"public",status:"active",published_at:new Date().toISOString()}:data.decision==="hide"?{visibility:"hidden",publication_status:"hidden"}:{moderation_status:"rejected",publication_status:"rejected",visibility:"hidden"};const {error}=await context.supabase.from("products").update(update).eq("id",data.productId);if(error)throw new Error(error.message);return {ok:true};});

export const updateHomepageSection=createServerFn({method:"POST"}).middleware(adminOnly).inputValidator(data=>z.object({sectionId:z.string().uuid(),enabled:z.boolean()}).parse(data)).handler(async({data,context})=>{await assertAdmin(context);const {error}=await context.supabase.from("homepage_sections").update({enabled:data.enabled}).eq("id",data.sectionId);if(error)throw new Error(error.message);return {ok:true};});
