import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { SiteFooter, SiteHeader } from "@/components/layout/site-shell";
import { supabase } from "@/integrations/supabase/client";
import { getLocale, getTranslations, localeDirections } from "@/lib/i18n";

export const Route = createFileRoute("/auth")({ validateSearch:(search:Record<string,unknown>)=>({locale:getLocale(typeof search.locale === "string" ? search.locale : undefined)}), component: AuthPage });
function AuthPage(){
 const {locale}=Route.useSearch(); const t=getTranslations(locale); const nav=useNavigate(); const [mode,setMode]=useState<"signin"|"signup">("signin"); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [name,setName]=useState(""); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setMessage("");try{if(mode==="signin"){const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;await nav({to:"/",search:{locale}});}else{const {data,error}=await supabase.auth.signUp({email,password,options:{data:{display_name:name}}});if(error)throw error;if(data.user){await supabase.from("profiles").upsert({id:data.user.id,display_name:name,preferred_locale:locale});}setMessage("Account created. If email confirmation is enabled, check your inbox before signing in.");}}catch(err){setMessage(err instanceof Error?err.message:"Authentication failed.");}finally{setLoading(false)}}
 return <div dir={localeDirections[locale]} lang={locale} className="min-h-screen bg-background"><SiteHeader locale={locale} t={t}/><main className="mx-auto flex min-h-[calc(100vh-16rem)] max-w-md items-center px-4 py-12"><form onSubmit={submit} className="w-full rounded-[30px] border border-border bg-card p-6 sm:p-8"><p className="text-eyebrow text-muted-foreground">MODALIA</p><h1 className="mt-2 text-display">{mode==="signin"?"Welcome back":"Create your account"}</h1><p className="mt-3 text-small text-muted-foreground">{mode==="signin"?"Sign in to manage orders, wishlist and seller tools.":"Create a Modalia account in seconds."}</p>{mode==="signup"?<label className="mt-7 block text-small">Name<Input className="mt-2" value={name} onChange={e=>setName(e.target.value)} required/></label>:null}<label className="mt-5 block text-small">Email<Input className="mt-2" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label className="mt-5 block text-small">Password<Input className="mt-2" type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/></label>{message?<p className="mt-5 rounded-xl bg-muted p-3 text-small">{message}</p>:null}<Button className="mt-6 h-12 w-full rounded-full" disabled={loading}>{loading?"Please wait…":mode==="signin"?"Sign in":"Create account"}</Button><button type="button" className="mt-5 w-full text-small underline underline-offset-4" onClick={()=>setMode(mode==="signin"?"signup":"signin")}>{mode==="signin"?"Need an account? Create one":"Already have an account? Sign in"}</button><Link to="/" search={{locale}} className="mt-5 block text-center text-caption text-muted-foreground">Back to Modalia</Link></form></main><SiteFooter t={t}/></div>
}
