import { createFileRoute, Link } from "@tanstack/react-router";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { ProductGrid } from "@/components/marketplace/discovery";
import { SiteFooter, SiteHeader } from "@/components/layout/site-shell";
import { browseCatalog } from "@/lib/catalog.functions";
import { getLocale, getTranslations, localeDirections } from "@/lib/i18n";

const categoryQuery = (slug: string) => queryOptions({ queryKey: ["category", slug], queryFn: () => browseCatalog({ data: { category: slug, sort: "newest", page: 1 } }) });
export const Route = createFileRoute("/category/$slug")({ validateSearch: (search: Record<string, unknown>) => ({ locale: getLocale(typeof search["locale"] === "string" ? search["locale"] : undefined) }), loaderDeps: ({ params }) => ({ slug: params.slug }), loader: ({ context, deps }) => context.queryClient.ensureQueryData(categoryQuery(deps.slug)), pendingComponent: () => <div className="px-6 py-24 text-center text-muted-foreground">Loading category…</div>, errorComponent: () => <div role="alert" className="px-6 py-24 text-center text-muted-foreground">This category could not be loaded.</div>, notFoundComponent: () => <div className="px-6 py-24 text-center text-muted-foreground">This category is not available.</div>, head: ({ params }) => ({ meta: [{ title: `${params.slug} — Modalia` }, { name: "description", content: "Browse this Modalia category." }, { property: "og:title", content: `${params.slug} — Modalia` }, { property: "og:description", content: "Browse this Modalia category." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: `/category/${params.slug}` }] }), component: CategoryPage });
function CategoryPage() { const { slug } = Route.useParams(); const { locale } = Route.useSearch(); const { data } = useSuspenseQuery(categoryQuery(slug)); const category = data.categories.find((item) => item.slug === slug); const t = getTranslations(locale); return <div dir={localeDirections[locale]} lang={locale} className="min-h-screen bg-background"><SiteHeader locale={locale} t={t} /><main className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><p className="text-eyebrow text-muted-foreground">Category</p><h1 className="mt-2 text-display text-foreground">{category?.name ?? slug}</h1><p className="mt-4 max-w-xl text-body text-muted-foreground">A considered edit from approved marketplace listings.</p><div className="mt-10"><ProductGrid products={data.products} locale={locale} emptyTitle="This category is just getting started" emptyText="New approved listings will appear here as stores add them." /></div><div className="mt-12"><Button asChild variant="outline"><Link to="/shop" search={{ locale, q: "", category: "", sort: "newest", page: 1, focus: "", view: "" }}>Browse all products</Link></Button></div></main><SiteFooter t={t} /></div>; }