import { createFileRoute, Link } from "@tanstack/react-router";
import { Check, Copy, Sparkles } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { SiteFooter, SiteHeader } from "@/components/layout/site-shell";
import { getLocale, getTranslations, localeDirections } from "@/lib/i18n";

export const Route=createFileRoute("/order-success")({
  head: () => ({ meta: [{ title: "Order received — Modalia" }, { name: "description", content: "Your Modalia cash-on-delivery order has been received." }, { property: "og:title", content: "Order received — Modalia" }, { property: "og:description", content: "Your Modalia cash-on-delivery order has been received." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),validateSearch:(search:Record<string,unknown>)=>({locale:getLocale(typeof search["locale"] === "string"?search["locale"]:undefined),order:typeof search["order"] === "string"?search["order"]:""}),component:OrderSuccessPage});
function OrderSuccessPage(){const {locale,order}=Route.useSearch();const t=getTranslations(locale);const [copied,setCopied]=useState(false);async function copy(){if(!order)return;await navigator.clipboard?.writeText(order);setCopied(true);setTimeout(()=>setCopied(false),1600)}return <div dir={localeDirections[locale]} lang={locale} className="min-h-screen bg-background"><SiteHeader locale={locale} t={t}/><main className="mx-auto flex min-h-[calc(100vh-16rem)] max-w-3xl items-center px-4 py-12"><div className="w-full text-center"><div className="success-orbit mx-auto grid size-24 place-items-center rounded-full bg-zinc-950 text-white"><Check className="size-10"/></div><p className="mt-8 text-eyebrow text-muted-foreground">Order received</p><h1 className="mt-3 text-[clamp(2.7rem,7vw,5.5rem)] font-semibold leading-[.9] tracking-[-.055em]">Your order is in.</h1><p className="mx-auto mt-5 max-w-xl text-body text-muted-foreground">Keep your order code safe. It identifies this purchase and can be used for future order services.</p>{order?<div className="mx-auto mt-8 flex max-w-sm items-center justify-between rounded-2xl border border-border bg-card p-2 pl-5"><span className="font-mono text-lg font-semibold tracking-widest">{order}</span><Button variant="ghost" size="sm" onClick={copy}>{copied?<Check/>:<Copy/>}{copied?"Copied":"Copy"}</Button></div>:null}<div className="mt-8 flex flex-wrap justify-center gap-3"><Button asChild><Link to="/shop" search={{locale,q:"",category:"",sort:"newest",page:1,focus:"",view:""}}>Continue shopping</Link></Button><Button asChild variant="outline"><Link to="/auth" search={{locale}}>Create / sign in</Link></Button></div><div className="mt-10 flex items-center justify-center gap-2 text-caption text-muted-foreground"><Sparkles className="size-3.5"/> Cash on Delivery · Server-validated order</div></div></main><SiteFooter locale={locale} t={t}/></div>}
