import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { Search, SlidersHorizontal } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ProductGrid } from "@/components/marketplace/discovery";
import { SiteFooter, SiteHeader } from "@/components/layout/site-shell";
import { browseCatalog } from "@/lib/catalog.functions";
import { getLocale, getTranslations, localeDirections } from "@/lib/i18n";

const shopQuery = (input: { q: string; category: string; sort: string; page: number }) => queryOptions({ queryKey: ["catalog", input], queryFn: () => browseCatalog({ data: input }) });
export const Route = createFileRoute("/shop")({ validateSearch: (search: Record<string, unknown>) => ({ locale: getLocale(typeof search["locale"] === "string" ? search["locale"] : undefined), q: typeof search["q"] === "string" ? search["q"] : "", category: typeof search["category"] === "string" ? search["category"] : "", sort: typeof search["sort"] === "string" ? search["sort"] : "newest", page: typeof search["page"] === "number" ? Math.max(1, search["page"]) : 1, focus: typeof search["focus"] === "string" ? search["focus"] : "", view: typeof search["view"] === "string" ? search["view"] : "" }), loaderDeps: ({ search }) => ({ q: search.q, category: search.category, sort: search.sort, page: search.page }), loader: ({ context, deps }) => context.queryClient.ensureQueryData(shopQuery(deps)), pendingComponent: () => <div className="px-6 py-24 text-center text-muted-foreground">Loading catalogue…</div>, errorComponent: () => <div role="alert" className="px-6 py-24 text-center text-muted-foreground">The catalogue could not be loaded. Please try again.</div>, notFoundComponent: () => <div className="px-6 py-24 text-center text-muted-foreground">No catalogue found.</div>, head: () => ({ meta: [{ title: "Shop — Modalia" }, { name: "description", content: "Browse approved products from Modalia’s independent stores." }, { property: "og:title", content: "Shop — Modalia" }, { property: "og:description", content: "Browse approved products from Modalia’s independent stores." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/shop" }] }), component: ShopPage });
function ShopPage() { const search = Route.useSearch(); const navigate = useNavigate({ from: "/shop" }); const { data } = useSuspenseQuery(shopQuery(search)); const t = getTranslations(search.locale); return <div dir={localeDirections[search.locale]} lang={search.locale} className="min-h-screen bg-background"><SiteHeader locale={search.locale} t={t} /><main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><p className="text-eyebrow text-muted-foreground">Modalia catalogue</p><h1 className="mt-2 text-display text-foreground">Discover more</h1><form onSubmit={(event) => { event.preventDefault(); const value = new FormData(event.currentTarget).get("q"); navigate({ search: (previous) => ({ ...previous, q: typeof value === "string" ? value : "", page: 1 }) }); }} className="relative mt-8 max-w-2xl"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input autoFocus={search.focus === "search"} name="q" defaultValue={search.q} placeholder="Search products, stores, categories and brands" className="h-11 pl-10" /></form><div className="mt-8 flex flex-wrap items-center justify-between gap-4 border-y border-border py-4"><div className="flex gap-2 overflow-x-auto"><Button variant={search.category === "" ? "default" : "outline"} size="sm" onClick={() => navigate({ search: (previous) => ({ ...previous, category: "", page: 1 }) })}>All</Button>{data.categories.map((category) => <Button key={category.id} variant={search.category === category.slug ? "default" : "outline"} size="sm" onClick={() => navigate({ search: (previous) => ({ ...previous, category: category.slug, page: 1 }) })}>{category.name}</Button>)}</div><div className="flex items-center gap-2"><SlidersHorizontal className="size-4 text-muted-foreground" /><select aria-label="Sort products" value={search.sort} onChange={(event) => navigate({ search: (previous) => ({ ...previous, sort: event.target.value, page: 1 }) })} className="h-9 bg-background text-small text-foreground outline-none"><option value="newest">Newest</option><option value="price_asc">Price: low to high</option><option value="price_desc">Price: high to low</option></select></div></div>{search.q ? <p className="mt-8 text-small text-muted-foreground">Results for “{search.q}”</p> : null}<div className="mt-8"><ProductGrid products={data.products} locale={search.locale} /></div>{data.products.length ? <div className="mt-12 flex justify-center"><Button asChild variant="outline"><Link to="/shop" search={{ ...search, page: search.page + 1 }}>Load more</Link></Button></div> : null}</main><SiteFooter t={t} /></div>; }