import { createFileRoute } from "@tanstack/react-router";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { BadgeCheck } from "lucide-react";
import { ProductGrid } from "@/components/marketplace/discovery";
import { SiteFooter, SiteHeader } from "@/components/layout/site-shell";
import { getStoreDetail } from "@/lib/store.functions";
import { getLocale, getTranslations, localeDirections } from "@/lib/i18n";

const storeQuery=(slug:string,locale:string)=>queryOptions({queryKey:["store",slug,locale],queryFn:()=>getStoreDetail({data:{slug,locale}})});
export const Route = createFileRoute("/store/$slug")({validateSearch:(search:Record<string,unknown>)=>({locale:getLocale(typeof search["locale"]==="string"?search["locale"]:undefined)}),loaderDeps:({search})=>({locale:search.locale}),loader:({context,params,deps})=>context.queryClient.ensureQueryData(storeQuery(params.slug,deps.locale)),head: ({ params }) => ({ meta: [{ title: `${params.slug} — Modalia` }, { name: "description", content: "Explore this independent store on Modalia." }, { property: "og:title", content: `${params.slug} — Modalia` }, { property: "og:description", content: "Explore this independent store on Modalia." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: `/store/${params.slug}` }] }),component: StorePage });
function StorePage(){const {slug}=Route.useParams();const {locale}=Route.useSearch();const {data:store}=useSuspenseQuery(storeQuery(slug,locale));const t=getTranslations(locale);if(!store)return <div dir={localeDirections[locale]} className="min-h-screen bg-background"><SiteHeader locale={locale} t={t}/><main className="mx-auto max-w-7xl px-4 py-24 text-center"><h1 className="text-display">Store unavailable</h1><p className="mt-3 text-body text-muted-foreground">This store is not currently open to customers.</p></main><SiteFooter t={t}/></div>;return <div dir={localeDirections[locale]} lang={locale} className="min-h-screen bg-background"><SiteHeader locale={locale} t={t}/><main><section className="border-b border-border"><div className="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:px-8"><div className="relative min-h-52 overflow-hidden bg-secondary sm:min-h-72">{store.bannerUrl?<img src={store.bannerUrl} alt="" className="size-full object-cover"/>:<div className="absolute inset-0 store-sheen"/>}</div><div className="relative -mt-12 flex flex-wrap items-end gap-5 px-5 sm:px-8"><div className="grid size-24 place-items-center overflow-hidden rounded-full border-4 border-background bg-card text-3xl font-semibold">{store.logoUrl?<img src={store.logoUrl} alt="" className="size-full object-cover"/>:store.name.slice(0,1)}</div><div className="pb-2"><div className="flex items-center gap-2"><h1 className="text-display">{store.name}</h1>{store.verified?<BadgeCheck className="size-5 text-foreground" aria-label="Verified store"/>:null}</div><p className="mt-1 text-small text-muted-foreground">Independent seller on Modalia</p></div></div><div className="max-w-2xl px-5 pb-2 pt-6 sm:px-8">{store.description?<p className="text-body text-muted-foreground">{store.description}</p>:null}{store.categories.length?<p className="mt-5 text-caption text-muted-foreground">{store.categories.join(" · ")}</p>:null}</div></div></section><section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><p className="text-eyebrow text-muted-foreground">Store catalogue</p><h2 className="mt-2 text-h3">All products</h2><div className="mt-8"><ProductGrid products={store.products} locale={locale} emptyTitle="This store is preparing its first products" emptyText="Approved listings will appear here when they are ready."/></div></section></main><SiteFooter t={t}/></div>}
