import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { SiteFooter, SiteHeader } from "@/components/layout/site-shell";
import { getLocale, getTranslations, localeDirections } from "@/lib/i18n";
import { trackGuestOrder } from "@/lib/orders.functions";

export const Route = createFileRoute("/track-order")({
  validateSearch:(search:Record<string,unknown>)=>({locale:getLocale(typeof search.locale==="string"?search.locale:undefined)}),
  head: () => ({ meta: [{ title: "Track order — Modalia" }, { name: "description", content: "Check the latest status of your Modalia order." }, { property: "og:title", content: "Track order — Modalia" }, { property: "og:description", content: "Check the latest status of your Modalia order." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/track-order" }] }),
  component: TrackOrderPage,
});
function TrackOrderPage(){const {locale}=Route.useSearch();const t=getTranslations(locale);const [orderNumber,setOrderNumber]=useState("");const [phone,setPhone]=useState("");const lookup=useMutation({mutationFn:()=>trackGuestOrder({data:{orderNumber,phone}})});return <div dir={localeDirections[locale]} lang={locale} className="min-h-screen bg-background"><SiteHeader locale={locale} t={t}/><main className="mx-auto max-w-xl px-4 py-14 sm:px-6"><p className="text-eyebrow text-muted-foreground">Order service</p><h1 className="mt-2 text-display">Track your order</h1><p className="mt-4 text-body text-muted-foreground">Enter the order code and the mobile number used at checkout.</p><form onSubmit={e=>{e.preventDefault();lookup.mutate()}} className="mt-8 border border-border bg-card p-6"><label className="block text-small">Order code<Input className="mt-2" value={orderNumber} placeholder="ORD-ABC123" onChange={e=>setOrderNumber(e.target.value.toUpperCase())} required/></label><label className="mt-4 block text-small">Mobile number<Input className="mt-2" value={phone} placeholder="+213551234567" onChange={e=>setPhone(e.target.value)} required/></label><Button className="mt-6" disabled={lookup.isPending}>{lookup.isPending?"Checking…":"Track order"}</Button></form>{lookup.isError?<p className="mt-5 text-small text-destructive">{lookup.error instanceof Error?lookup.error.message:"We could not check this order."}</p>:null}{lookup.isSuccess&&!lookup.data?<p className="mt-5 border border-border p-4 text-small text-muted-foreground">No matching order was found. Check the code and mobile number.</p>:null}{lookup.data?<section className="mt-6 border border-border bg-card p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-caption text-muted-foreground">{lookup.data.orderNumber}</p><h2 className="mt-1 text-h3">{lookup.data.status.replaceAll("_"," ")}</h2></div><p className="text-price">{new Intl.NumberFormat(locale,{style:"currency",currency:lookup.data.currency}).format(lookup.data.total)}</p></div><p className="mt-4 text-small text-muted-foreground">{lookup.data.deliveryMethod === "office" ? "Office / pickup delivery" : "Home delivery"} · Placed {new Intl.DateTimeFormat(locale,{dateStyle:"medium"}).format(new Date(lookup.data.createdAt))}</p><div className="mt-5 divide-y divide-border">{lookup.data.sellerOrders.map((sellerOrder:{storeName:string;status:string})=><div key={`${sellerOrder.storeName}-${sellerOrder.status}`} className="flex justify-between py-3 text-small"><span>{sellerOrder.storeName}</span><span className="capitalize text-muted-foreground">{sellerOrder.status.replaceAll("_"," ")}</span></div>)}</div></section>:null}</main><SiteFooter t={t}/></div>}
