import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Heart, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SiteFooter, SiteHeader } from "@/components/layout/site-shell";
import { formatPrice } from "@/lib/localization";
import { getLocale, getTranslations, localeDirections } from "@/lib/i18n";
import { readWishlist, toggleWishlist, type WishlistItem } from "@/lib/wishlist-store";

export const Route=createFileRoute("/wishlist")({
  head: () => ({ meta: [{ title: "Wishlist — Modalia" }, { name: "description", content: "Saved Modalia products ready to revisit." }, { property: "og:title", content: "Wishlist — Modalia" }, { property: "og:description", content: "Saved Modalia products ready to revisit." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),validateSearch:(search:Record<string,unknown>)=>({locale:getLocale(typeof search.locale === "string"?search.locale:undefined)}),component:WishlistPage});
function WishlistPage(){const {locale}=Route.useSearch();const t=getTranslations(locale);const [items,setItems]=useState<WishlistItem[]>([]);useEffect(()=>setItems(readWishlist()),[]);function remove(item:WishlistItem){toggleWishlist(item);setItems(readWishlist())}return <div dir={localeDirections[locale]} lang={locale} className="min-h-screen bg-background"><SiteHeader locale={locale} t={t}/><main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><p className="text-eyebrow text-muted-foreground">Saved</p><h1 className="mt-2 text-display">Wishlist</h1><p className="mt-3 text-body text-muted-foreground">Keep products you want to revisit. Your list stays on this device until you sign in.</p>{!items.length?<section className="mt-10 rounded-[30px] border border-border p-12 text-center"><Heart className="mx-auto size-8"/><h2 className="mt-5 text-h3">Nothing saved yet</h2><Button asChild className="mt-6"><Link to="/shop" search={{locale,q:"",category:"",sort:"newest",page:1,focus:"",view:""}}>Discover products</Link></Button></section>:<div className="mt-10 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">{items.map(item=><article key={item.productId} className="group rounded-[24px] border border-border bg-card p-2"><Link to="/product/$slug" params={{slug:item.slug}} search={{locale}}><div className="aspect-[4/5] overflow-hidden rounded-[18px] bg-muted">{item.image?<img src={item.image} alt={item.name} className="size-full object-cover transition-transform duration-700 group-hover:scale-[1.03]"/>:null}</div><div className="p-3"><p className="text-caption text-muted-foreground">{item.storeName}</p><h3 className="mt-1 line-clamp-2 text-small font-medium">{item.name}</h3><p className="mt-2 font-semibold">{formatPrice(item.price,locale)}</p></div></Link><Button variant="ghost" size="sm" className="w-full" onClick={()=>remove(item)}><Trash2/>Remove</Button></article>)}</div>}</main><SiteFooter t={t}/></div>}
