import { Link } from "@tanstack/react-router";
import { ArrowRight, Heart, Search, ShoppingBag } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { formatPrice } from "@/lib/localization";
import type { CatalogCategory, CatalogProduct, CatalogStore } from "@/lib/catalog.functions";
import type { SupportedLocale } from "@/config/platform";

export function ProductCard({ product, locale }: { product: CatalogProduct; locale: SupportedLocale }) {
  return <article className="group min-w-0"><Link to="/product/$slug" params={{ slug: product.slug }} className="block"><div className="relative aspect-[4/5] overflow-hidden bg-muted">{product.imagePath ? <img src={product.imagePath} alt={product.imageAlt || product.name} loading="lazy" sizes="(min-width: 1024px) 25vw, 50vw" className="size-full object-cover transition-transform duration-500 ease-out group-hover:scale-[1.03] motion-reduce:transition-none" /> : <div className="flex size-full items-end p-5 text-small text-muted-foreground">Modalia<br />{product.name}</div>}<Button type="button" variant="ghost" size="icon" aria-label={`Save ${product.name}`} className="absolute right-2 top-2 bg-background/80 opacity-0 backdrop-blur-sm transition-opacity group-hover:opacity-100 focus-visible:opacity-100"><Heart /></Button></div><div className="mt-3"><p className="text-caption text-muted-foreground">{product.storeName}</p><h3 className="mt-1 line-clamp-1 text-body font-medium text-foreground">{product.name}</h3><p className="mt-1 text-price text-foreground">{formatPrice(product.price, locale)}</p></div></Link></article>;
}

export function CategoryRail({ categories, locale }: { categories: CatalogCategory[]; locale: SupportedLocale }) { return <div className="flex gap-3 overflow-x-auto pb-2 lg:grid lg:grid-cols-6 lg:overflow-visible">{categories.map((category, index) => <Link key={category.id} to="/category/$slug" params={{ slug: category.slug }} search={{ locale }} className={`group min-w-40 border border-border p-4 transition-colors hover:bg-muted lg:min-w-0 ${index === 0 ? "lg:col-span-2 lg:row-span-2 lg:flex lg:min-h-64 lg:flex-col lg:justify-end" : ""}`}><p className="text-h3 text-foreground">{category.name}</p><p className="mt-1 text-caption text-muted-foreground">{category.productCount} {category.productCount === 1 ? "product" : "products"}</p><ArrowRight className="mt-5 size-4 text-muted-foreground transition-transform group-hover:translate-x-1 rtl:rotate-180 rtl:group-hover:-translate-x-1" /></Link>)}</div>; }

export function StoreRail({ stores }: { stores: CatalogStore[] }) { return <div className="grid gap-px border border-border bg-border sm:grid-cols-2 lg:grid-cols-3">{stores.map((store) => <Link key={store.id} to="/store/$slug" params={{ slug: store.slug }} className="group min-h-48 bg-background p-5 transition-colors hover:bg-muted"><div className="flex items-center gap-3">{store.logoPath ? <img src={store.logoPath} alt="" className="size-10 rounded-full object-cover" loading="lazy" /> : <div className="flex size-10 items-center justify-center rounded-full bg-secondary text-small font-medium">{store.name.slice(0, 1)}</div>}<div><h3 className="text-h3 text-foreground">{store.name}</h3><p className="text-caption text-muted-foreground">{store.productCount} products</p></div></div>{store.description ? <p className="mt-7 line-clamp-2 text-small text-muted-foreground">{store.description}</p> : null}<ArrowRight className="mt-6 size-4 text-muted-foreground transition-transform group-hover:translate-x-1 rtl:rotate-180 rtl:group-hover:-translate-x-1" /></Link>)}</div>; }

export function ProductGrid({ products, locale, emptyTitle = "No products found", emptyText = "Try changing your search or browse another category." }: { products: CatalogProduct[]; locale: SupportedLocale; emptyTitle?: string; emptyText?: string }) { if (!products.length) return <section className="border-y border-border py-16 text-center"><ShoppingBag className="mx-auto size-6 text-muted-foreground" /><h2 className="mt-4 text-h3 text-foreground">{emptyTitle}</h2><p className="mx-auto mt-2 max-w-sm text-small text-muted-foreground">{emptyText}</p></section>; return <div className="grid grid-cols-2 gap-x-3 gap-y-8 sm:grid-cols-3 lg:grid-cols-4 lg:gap-x-5">{products.map((product) => <ProductCard key={product.id} product={product} locale={locale} />)}</div>; }

export function DiscoverySkeleton() { return <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><Skeleton className="h-[28rem] w-full" /><div className="mt-16 grid grid-cols-2 gap-3 lg:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <div key={index}><Skeleton className="aspect-[4/5] w-full" /><Skeleton className="mt-3 h-4 w-2/3" /><Skeleton className="mt-2 h-4 w-1/3" /></div>)}</div></div>; }

export function SearchEmpty({ query }: { query: string }) { return <section className="py-16 text-center"><Search className="mx-auto size-6 text-muted-foreground" /><h1 className="mt-4 text-display text-foreground">No matches for “{query}”</h1><p className="mx-auto mt-3 max-w-sm text-body text-muted-foreground">Search products, stores, categories, and brands as the marketplace grows.</p></section>; }