import { Copy, PackageCheck, ReceiptText } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { formatPrice } from "@/lib/localization";
import type { SupportedLocale } from "@/config/platform";
import type { CustomerOrderCard, CustomerOrderDetail, SellerOrderCard } from "@/lib/orders.functions";

function statusLabel(status: string) { return status.replaceAll("_", " "); }
function addressName(address: unknown, key: "wilaya" | "commune") { if (!address || Array.isArray(address) || typeof address !== "object") return ""; const value = (address as Record<string, unknown>)[key]; if (!value || Array.isArray(value) || typeof value !== "object") return typeof value === "string" ? value : ""; const labels = value as Record<string, unknown>; return typeof labels["fr"] === "string" ? labels["fr"] : typeof labels["en"] === "string" ? labels["en"] : typeof labels["ar"] === "string" ? labels["ar"] : ""; }

export function OrderList({ orders, locale }: { orders: CustomerOrderCard[]; locale: SupportedLocale }) { return <div className="divide-y divide-border border-y border-border">{orders.map((order) => <article key={order.id} className="grid gap-4 py-5 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="text-nav text-foreground">{order.orderNumber}</p><p className="mt-1 text-small text-muted-foreground">{new Intl.DateTimeFormat(locale === "ar" ? "ar-DZ" : `${locale}-DZ`, { dateStyle: "medium" }).format(new Date(order.createdAt))} · {order.itemCount} item{order.itemCount === 1 ? "" : "s"}</p></div><div className="flex items-center justify-between gap-5 sm:justify-end"><div className="text-end"><p className="text-price text-foreground">{formatPrice(order.total, locale)}</p><p className="mt-1 capitalize text-caption text-muted-foreground">{statusLabel(order.status)}</p></div><Button asChild variant="outline" size="sm"><Link to="/account/orders/$orderId" params={{ orderId: order.id }} search={{ locale }}>View</Link></Button></div></article>)}</div>; }

export function OrderDetailView({ order, locale }: { order: CustomerOrderDetail; locale: SupportedLocale }) { const addressLine = order.address && !Array.isArray(order.address) && typeof order.address === "object" ? (order.address as Record<string, unknown>)["address_line"] : ""; return <main className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-eyebrow text-muted-foreground">Order</p><h1 className="mt-2 text-display text-foreground">{order.orderNumber}</h1><p className="mt-3 capitalize text-body text-muted-foreground">{statusLabel(order.status)}</p></div><p className="text-price text-foreground">{formatPrice(order.total, locale)}</p></div><section className="mt-10"><h2 className="text-h3 text-foreground">Items</h2><div className="mt-4 divide-y divide-border border-y border-border">{order.items.map((item) => <article key={item.id} className="flex gap-4 py-4"><div className="size-16 shrink-0 overflow-hidden bg-muted">{item.imagePath ? <img src={item.imagePath} alt="" className="size-full object-cover" /> : null}</div><div className="min-w-0 flex-1"><p className="text-nav text-foreground">{item.title}</p><p className="mt-1 text-small text-muted-foreground">Quantity {item.quantity}{item.sku ? ` · ${item.sku}` : ""}</p></div><p className="text-price text-foreground">{formatPrice(item.total, locale)}</p></article>)}</div></section><div className="mt-10 grid gap-8 md:grid-cols-2"><section><h2 className="text-h3 text-foreground">Delivery</h2><p className="mt-3 text-small text-muted-foreground">{typeof addressLine === "string" ? addressLine : ""}<br />{addressName(order.address, "commune")} {addressName(order.address, "wilaya")}</p><p className="mt-3 text-small capitalize text-muted-foreground">{order.deliveryMethod === "office" ? "Office / pickup" : "Home delivery"}</p></section><section><h2 className="text-h3 text-foreground">Payment</h2><p className="mt-3 text-small text-muted-foreground">Cash on Delivery · {order.paymentStatus}</p><dl className="mt-5 space-y-2 text-small"><div className="flex justify-between gap-4"><dt className="text-muted-foreground">Products</dt><dd>{formatPrice(order.subtotal, locale)}</dd></div><div className="flex justify-between gap-4"><dt className="text-muted-foreground">Shipping</dt><dd>{formatPrice(order.shippingTotal, locale)}</dd></div><div className="flex justify-between gap-4 border-t border-border pt-2 text-nav"><dt>Total</dt><dd>{formatPrice(order.total, locale)}</dd></div></dl></section></div></main>; }

export function ConfirmationView({ orderNumber, total, deliveryMethod, address, locale }: { orderNumber: string; total: number; deliveryMethod: string | null; address: unknown; locale: SupportedLocale }) { const copy = async () => { await navigator.clipboard?.writeText(orderNumber); }; return <main className="mx-auto flex min-h-[calc(100vh-16rem)] max-w-3xl items-center px-4 py-10 sm:px-6"><div className="w-full text-center"><div className="mx-auto flex size-16 items-center justify-center rounded-full bg-secondary motion-safe:animate-in motion-safe:zoom-in"><PackageCheck className="size-8 text-foreground" /></div><p className="mt-7 text-eyebrow text-muted-foreground">Order confirmed</p><h1 className="mt-3 text-display text-foreground">Thank you for your order.</h1><p className="mx-auto mt-4 max-w-lg text-body text-muted-foreground">Keep your order code to track your order when tracking becomes available.</p><div className="mx-auto mt-8 flex max-w-sm items-center justify-between border border-border bg-card p-4 text-start"><div><p className="text-caption text-muted-foreground">Order code</p><p className="mt-1 text-h3 text-foreground">{orderNumber}</p></div><Button type="button" variant="outline" size="icon" aria-label="Copy order code" onClick={copy}><Copy /></Button></div><div className="mx-auto mt-6 grid max-w-sm gap-3 border-y border-border py-5 text-small"><div className="flex justify-between gap-4"><span className="text-muted-foreground">Total</span><span className="text-price">{formatPrice(total, locale)}</span></div><div className="flex justify-between gap-4"><span className="text-muted-foreground">Delivery</span><span>{deliveryMethod === "office" ? "Office / pickup" : "Home delivery"}</span></div><div className="flex justify-between gap-4"><span className="text-muted-foreground">Destination</span><span>{addressName(address, "commune")} {addressName(address, "wilaya")}</span></div><div className="flex justify-between gap-4"><span className="text-muted-foreground">Payment</span><span>Cash on Delivery</span></div></div><div className="mt-8 flex flex-wrap justify-center gap-3"><Button asChild><Link to="/shop" search={{ locale, q: "", category: "", sort: "newest", page: 1, focus: "", view: "" }}>Continue shopping</Link></Button><Button asChild variant="outline"><Link to="/account/orders" search={{ locale }}>View my orders</Link></Button></div></div></main>; }

export function SellerOrdersList({ orders, locale }: { orders: SellerOrderCard[]; locale: SupportedLocale }) { return <div className="divide-y divide-border border-y border-border">{orders.map((order) => <article key={order.id} className="grid gap-3 py-4 sm:grid-cols-[1fr_auto_auto]"><div><p className="text-nav text-foreground">{order.orderNumber}</p><p className="mt-1 text-small text-muted-foreground">{order.customerName} · {order.itemCount} items</p></div><p className="text-small capitalize text-muted-foreground sm:text-end">{statusLabel(order.status)}<br />{order.deliveryMethod === "office" ? "Office / pickup" : "Home delivery"}</p><p className="text-price text-foreground sm:text-end">{formatPrice(order.total, locale)}</p></article>)}</div>; }

export function OrdersEmpty() { return <div className="border-y border-border py-16 text-center"><ReceiptText className="mx-auto size-7 text-muted-foreground" /><h2 className="mt-4 text-h3 text-foreground">No orders yet</h2><p className="mt-2 text-small text-muted-foreground">Your completed purchases will appear here.</p></div>; }