import { ReceiptText } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { formatDate, formatPrice } from "@/lib/i18n/format";
import { getTranslations } from "@/lib/i18n";
import type { SupportedLocale } from "@/config/platform";
import type { CustomerOrderCard, CustomerOrderDetail } from "@/lib/orders.functions";

function addressName(address: unknown, key: "wilaya" | "commune", locale: SupportedLocale) { if (!address || Array.isArray(address) || typeof address !== "object") return ""; const value = (address as Record<string, unknown>)[key]; if (!value || Array.isArray(value) || typeof value !== "object") return typeof value === "string" ? value : ""; const labels = value as Record<string, unknown>; for (const code of [locale, "fr", "en", "ar"]) { if (typeof labels[code] === "string") return labels[code] as string; } return ""; }

export function OrderList({ orders, locale }: { orders: CustomerOrderCard[]; locale: SupportedLocale }) { const t = getTranslations(locale).orders; return <div className="divide-y divide-border border-y border-border">{orders.map((order) => <article key={order.id} className="grid gap-4 py-5 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="text-nav text-foreground">{order.orderNumber}</p><p className="mt-1 text-small text-muted-foreground">{formatDate(order.createdAt, locale)} · {t.itemsCount(order.itemCount)}</p></div><div className="flex items-center justify-between gap-5 sm:justify-end"><div className="text-end"><p className="text-price text-foreground">{formatPrice(order.total, locale)}</p><p className="mt-1 text-caption text-muted-foreground">{t.statusLabel(order.status)}</p></div><Button asChild variant="outline" size="sm"><Link to="/account/orders/$orderId" params={{ orderId: order.id }} search={{ locale }}>{t.view}</Link></Button></div></article>)}</div>; }

export function OrderDetailView({ order, locale }: { order: CustomerOrderDetail; locale: SupportedLocale }) { const full = getTranslations(locale); const t = full.orders; const tc = full.checkout; const addressLine = order.address && !Array.isArray(order.address) && typeof order.address === "object" ? (order.address as Record<string, unknown>)["address_line"] : ""; return <main className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-eyebrow text-muted-foreground">{t.orderEyebrow}</p><h1 className="mt-2 text-display text-foreground">{order.orderNumber}</h1><p className="mt-3 text-body text-muted-foreground">{t.statusLabel(order.status)}</p></div><p className="text-price text-foreground">{formatPrice(order.total, locale)}</p></div><section className="mt-10"><h2 className="text-h3 text-foreground">{t.items}</h2><div className="mt-4 divide-y divide-border border-y border-border">{order.items.map((item) => <article key={item.id} className="flex gap-4 py-4"><div className="size-16 shrink-0 overflow-hidden bg-muted">{item.imagePath ? <img src={item.imagePath} alt="" className="size-full object-cover" /> : null}</div><div className="min-w-0 flex-1"><p className="text-nav text-foreground">{item.title}</p><p className="mt-1 text-small text-muted-foreground">{t.quantity} {item.quantity}{item.sku ? ` · ${item.sku}` : ""}</p></div><p className="text-price text-foreground">{formatPrice(item.total, locale)}</p></article>)}</div></section><div className="mt-10 grid gap-8 md:grid-cols-2"><section><h2 className="text-h3 text-foreground">{t.delivery}</h2><p className="mt-3 text-small text-muted-foreground">{typeof addressLine === "string" ? addressLine : ""}<br />{addressName(order.address, "commune", locale)} {addressName(order.address, "wilaya", locale)}</p><p className="mt-3 text-small text-muted-foreground">{order.deliveryMethod === "office" ? tc.officePickup : tc.homeDelivery}</p></section><section><h2 className="text-h3 text-foreground">{t.payment}</h2><p className="mt-3 text-small text-muted-foreground">{t.cashOnDelivery} · {t.paymentStatusLabel(order.paymentStatus)}</p><dl className="mt-5 space-y-2 text-small"><div className="flex justify-between gap-4"><dt className="text-muted-foreground">{t.products}</dt><dd>{formatPrice(order.subtotal, locale)}</dd></div><div className="flex justify-between gap-4"><dt className="text-muted-foreground">{t.shipping}</dt><dd>{formatPrice(order.shippingTotal, locale)}</dd></div><div className="flex justify-between gap-4 border-t border-border pt-2 text-nav"><dt>{t.total}</dt><dd>{formatPrice(order.total, locale)}</dd></div></dl></section></div></main>; }



export function OrdersEmpty({ locale }: { locale: SupportedLocale }) { const t = getTranslations(locale).orders; return <div className="border-y border-border py-16 text-center"><ReceiptText className="mx-auto size-7 text-muted-foreground" /><h2 className="mt-4 text-h3 text-foreground">{t.emptyTitle}</h2><p className="mt-2 text-small text-muted-foreground">{t.emptyText}</p></div>; }
