import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { Menu, Search, ShoppingBag, UserRound, Heart, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { type SupportedLocale } from "@/config/platform";
import { localeLabels, type Translation } from "@/lib/i18n";

const footerGroups = [["About", "Customer service", "Shipping", "Returns"], ["Become a seller", "Contact", "Privacy", "Terms"]];
export function SiteHeader({ locale, t }: { locale: SupportedLocale; t: Translation }) { const [open, setOpen] = useState(false); return <header className="border-b border-border bg-background"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8"><Link to="/" search={{ locale }} className="text-wordmark text-foreground">Modalia</Link><nav className="hidden items-center gap-7 lg:flex" aria-label="Main navigation"><Link to="/shop" className="text-nav text-muted-foreground hover:text-foreground">{t.nav.shop}</Link><Link to="/become-a-seller" className="text-nav text-muted-foreground hover:text-foreground">{t.nav.sellers}</Link></nav><div className="flex items-center gap-1"><Button variant="ghost" size="icon" aria-label={t.nav.search}><Search /></Button><Button variant="ghost" size="icon" className="hidden sm:inline-flex" aria-label={t.nav.wishlist}><Heart /></Button><Link to="/cart"><Button variant="ghost" size="icon" aria-label={t.nav.cart}><ShoppingBag /></Button></Link><Button variant="ghost" size="icon" className="hidden sm:inline-flex" aria-label={t.nav.account}><UserRound /></Button><Button variant="ghost" size="icon" className="lg:hidden" aria-label={open ? "Close menu" : t.nav.menu} onClick={() => setOpen((value) => !value)}>{open ? <X /> : <Menu />}</Button></div></div>{open ? <nav className="border-t border-border px-4 py-4 lg:hidden" aria-label="Mobile navigation"><div className="mx-auto flex max-w-7xl flex-col gap-3"><Link to="/shop" onClick={() => setOpen(false)} className="text-nav">{t.nav.shop}</Link><Link to="/become-a-seller" onClick={() => setOpen(false)} className="text-nav">{t.nav.sellers}</Link><div className="pt-2 text-caption text-muted-foreground">{localeLabels[locale]}</div></div></nav> : null}</header>; }
export function SiteFooter({ t }: { t: Translation }) { return <footer className="border-t border-border bg-card"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-12 sm:px-6 md:grid-cols-[1.5fr_1fr_1fr] lg:px-8"><div><Link to="/" search={{ locale: "fr" }} className="text-wordmark text-foreground">Modalia</Link><p className="mt-4 max-w-xs text-body text-muted-foreground">{t.footer.statement}</p></div>{footerGroups.map((group) => <ul key={group[0]} className="space-y-3 text-small text-muted-foreground">{group.map((item) => <li key={item}><span>{item}</span></li>)}</ul>)}</div><div className="border-t border-border px-4 py-5 text-caption text-muted-foreground sm:px-6 lg:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between">© {new Date().getFullYear()} Modalia <span>{t.footer.newsletter}</span></div></div></footer>; }
