/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BecomeASellerRouteImport } from './routes/become-a-seller'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HelpRouteImport } from './routes/help'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AuthenticatedSellerRouteImport } from './routes/_authenticated/seller'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminCouponsRouteImport } from './routes/admin/coupons'
import { Route as AdminHomepageRouteImport } from './routes/admin/homepage'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminSellersRouteImport } from './routes/admin/sellers'
import { Route as AdminSettlementsRouteImport } from './routes/admin/settlements'
import { Route as AdminShippingRouteImport } from './routes/admin/shipping'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as AuthenticatedAccountOrdersRouteImport } from './routes/_authenticated/account.orders'
import { Route as AuthenticatedSellerAiRouteImport } from './routes/_authenticated/seller.ai'
import { Route as AuthenticatedSellerAnalyticsRouteImport } from './routes/_authenticated/seller.analytics'
import { Route as AuthenticatedSellerAppearanceRouteImport } from './routes/_authenticated/seller.appearance'
import { Route as AuthenticatedSellerBundlesRouteImport } from './routes/_authenticated/seller.bundles'
import { Route as AuthenticatedSellerCommissionRouteImport } from './routes/_authenticated/seller.commission'
import { Route as AuthenticatedSellerCouponsRouteImport } from './routes/_authenticated/seller.coupons'
import { Route as AuthenticatedSellerCustomersRouteImport } from './routes/_authenticated/seller.customers'
import { Route as AuthenticatedSellerInventoryRouteImport } from './routes/_authenticated/seller.inventory'
import { Route as AuthenticatedSellerOrdersRouteImport } from './routes/_authenticated/seller.orders'
import { Route as AuthenticatedSellerProductsRouteImport } from './routes/_authenticated/seller.products'
import { Route as AuthenticatedSellerPromotionsRouteImport } from './routes/_authenticated/seller.promotions'
import { Route as AuthenticatedSellerReviewsRouteImport } from './routes/_authenticated/seller.reviews'
import { Route as AuthenticatedSellerSettingsRouteImport } from './routes/_authenticated/seller.settings'
import { Route as AuthenticatedSellerSettlementsRouteImport } from './routes/_authenticated/seller.settlements'
import { Route as AuthenticatedSellerShippingRouteImport } from './routes/_authenticated/seller.shipping'
import { Route as AuthenticatedSellerStaffRouteImport } from './routes/_authenticated/seller.staff'
import { Route as AuthenticatedSellerStoreRouteImport } from './routes/_authenticated/seller.store'
import { Route as AuthenticatedSellerSupportRouteImport } from './routes/_authenticated/seller.support'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin/orders.$orderId'
import { Route as AdminSellersSellerIdRouteImport } from './routes/admin/sellers.$sellerId'
import { Route as AuthenticatedAccountOrdersOrderIdRouteImport } from './routes/_authenticated/account.orders.$orderId'
import { Route as AuthenticatedSellerOrdersOrderIdRouteImport } from './routes/_authenticated/seller.orders.$orderId'
import { Route as AuthenticatedSellerProductsProductIdRouteImport } from './routes/_authenticated/seller.products.$productId'
import { Route as AuthenticatedSellerProductsNewRouteImport } from './routes/_authenticated/seller.products.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeASellerRoute = BecomeASellerRouteImport.update({
  id: '/become-a-seller',
  path: '/become-a-seller',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSellerRoute = AuthenticatedSellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/admin/coupons',
  path: '/admin/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/admin/homepage',
  path: '/admin/homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSellersRoute = AdminSellersRouteImport.update({
  id: '/admin/sellers',
  path: '/admin/sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettlementsRoute = AdminSettlementsRouteImport.update({
  id: '/admin/settlements',
  path: '/admin/settlements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/admin/shipping',
  path: '/admin/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountOrdersRoute =
  AuthenticatedAccountOrdersRouteImport.update({
    id: '/account/orders',
    path: '/account/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSellerAiRoute = AuthenticatedSellerAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedSellerRoute,
} as any)
const AuthenticatedSellerAnalyticsRoute =
  AuthenticatedSellerAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerAppearanceRoute =
  AuthenticatedSellerAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerBundlesRoute =
  AuthenticatedSellerBundlesRouteImport.update({
    id: '/bundles',
    path: '/bundles',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerCommissionRoute =
  AuthenticatedSellerCommissionRouteImport.update({
    id: '/commission',
    path: '/commission',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerCouponsRoute =
  AuthenticatedSellerCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerCustomersRoute =
  AuthenticatedSellerCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerInventoryRoute =
  AuthenticatedSellerInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerOrdersRoute =
  AuthenticatedSellerOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerProductsRoute =
  AuthenticatedSellerProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerPromotionsRoute =
  AuthenticatedSellerPromotionsRouteImport.update({
    id: '/promotions',
    path: '/promotions',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerReviewsRoute =
  AuthenticatedSellerReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerSettingsRoute =
  AuthenticatedSellerSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerSettlementsRoute =
  AuthenticatedSellerSettlementsRouteImport.update({
    id: '/settlements',
    path: '/settlements',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerShippingRoute =
  AuthenticatedSellerShippingRouteImport.update({
    id: '/shipping',
    path: '/shipping',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerStaffRoute =
  AuthenticatedSellerStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerStoreRoute =
  AuthenticatedSellerStoreRouteImport.update({
    id: '/store',
    path: '/store',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerSupportRoute =
  AuthenticatedSellerSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminSellersSellerIdRoute = AdminSellersSellerIdRouteImport.update({
  id: '/$sellerId',
  path: '/$sellerId',
  getParentRoute: () => AdminSellersRoute,
} as any)
const AuthenticatedAccountOrdersOrderIdRoute =
  AuthenticatedAccountOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedAccountOrdersRoute,
  } as any)
const AuthenticatedSellerOrdersOrderIdRoute =
  AuthenticatedSellerOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedSellerOrdersRoute,
  } as any)
const AuthenticatedSellerProductsProductIdRoute =
  AuthenticatedSellerProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AuthenticatedSellerProductsRoute,
  } as any)
const AuthenticatedSellerProductsNewRoute =
  AuthenticatedSellerProductsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSellerProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/become-a-seller': typeof BecomeASellerRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/order-success': typeof OrderSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/seller': typeof AuthenticatedSellerRouteWithChildren
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sellers': typeof AdminSellersRouteWithChildren
  '/admin/settlements': typeof AdminSettlementsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRouteWithChildren
  '/seller/ai': typeof AuthenticatedSellerAiRoute
  '/seller/analytics': typeof AuthenticatedSellerAnalyticsRoute
  '/seller/appearance': typeof AuthenticatedSellerAppearanceRoute
  '/seller/bundles': typeof AuthenticatedSellerBundlesRoute
  '/seller/commission': typeof AuthenticatedSellerCommissionRoute
  '/seller/coupons': typeof AuthenticatedSellerCouponsRoute
  '/seller/customers': typeof AuthenticatedSellerCustomersRoute
  '/seller/inventory': typeof AuthenticatedSellerInventoryRoute
  '/seller/orders': typeof AuthenticatedSellerOrdersRouteWithChildren
  '/seller/products': typeof AuthenticatedSellerProductsRouteWithChildren
  '/seller/promotions': typeof AuthenticatedSellerPromotionsRoute
  '/seller/reviews': typeof AuthenticatedSellerReviewsRoute
  '/seller/settings': typeof AuthenticatedSellerSettingsRoute
  '/seller/settlements': typeof AuthenticatedSellerSettlementsRoute
  '/seller/shipping': typeof AuthenticatedSellerShippingRoute
  '/seller/staff': typeof AuthenticatedSellerStaffRoute
  '/seller/store': typeof AuthenticatedSellerStoreRoute
  '/seller/support': typeof AuthenticatedSellerSupportRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/sellers/$sellerId': typeof AdminSellersSellerIdRoute
  '/account/orders/$orderId': typeof AuthenticatedAccountOrdersOrderIdRoute
  '/seller/orders/$orderId': typeof AuthenticatedSellerOrdersOrderIdRoute
  '/seller/products/$productId': typeof AuthenticatedSellerProductsProductIdRoute
  '/seller/products/new': typeof AuthenticatedSellerProductsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/become-a-seller': typeof BecomeASellerRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/order-success': typeof OrderSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/seller': typeof AuthenticatedSellerRouteWithChildren
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sellers': typeof AdminSellersRouteWithChildren
  '/admin/settlements': typeof AdminSettlementsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/admin': typeof AdminIndexRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRouteWithChildren
  '/seller/ai': typeof AuthenticatedSellerAiRoute
  '/seller/analytics': typeof AuthenticatedSellerAnalyticsRoute
  '/seller/appearance': typeof AuthenticatedSellerAppearanceRoute
  '/seller/bundles': typeof AuthenticatedSellerBundlesRoute
  '/seller/commission': typeof AuthenticatedSellerCommissionRoute
  '/seller/coupons': typeof AuthenticatedSellerCouponsRoute
  '/seller/customers': typeof AuthenticatedSellerCustomersRoute
  '/seller/inventory': typeof AuthenticatedSellerInventoryRoute
  '/seller/orders': typeof AuthenticatedSellerOrdersRouteWithChildren
  '/seller/products': typeof AuthenticatedSellerProductsRouteWithChildren
  '/seller/promotions': typeof AuthenticatedSellerPromotionsRoute
  '/seller/reviews': typeof AuthenticatedSellerReviewsRoute
  '/seller/settings': typeof AuthenticatedSellerSettingsRoute
  '/seller/settlements': typeof AuthenticatedSellerSettlementsRoute
  '/seller/shipping': typeof AuthenticatedSellerShippingRoute
  '/seller/staff': typeof AuthenticatedSellerStaffRoute
  '/seller/store': typeof AuthenticatedSellerStoreRoute
  '/seller/support': typeof AuthenticatedSellerSupportRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/sellers/$sellerId': typeof AdminSellersSellerIdRoute
  '/account/orders/$orderId': typeof AuthenticatedAccountOrdersOrderIdRoute
  '/seller/orders/$orderId': typeof AuthenticatedSellerOrdersOrderIdRoute
  '/seller/products/$productId': typeof AuthenticatedSellerProductsProductIdRoute
  '/seller/products/new': typeof AuthenticatedSellerProductsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/become-a-seller': typeof BecomeASellerRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/order-success': typeof OrderSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/_authenticated/seller': typeof AuthenticatedSellerRouteWithChildren
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sellers': typeof AdminSellersRouteWithChildren
  '/admin/settlements': typeof AdminSettlementsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/account/orders': typeof AuthenticatedAccountOrdersRouteWithChildren
  '/_authenticated/seller/ai': typeof AuthenticatedSellerAiRoute
  '/_authenticated/seller/analytics': typeof AuthenticatedSellerAnalyticsRoute
  '/_authenticated/seller/appearance': typeof AuthenticatedSellerAppearanceRoute
  '/_authenticated/seller/bundles': typeof AuthenticatedSellerBundlesRoute
  '/_authenticated/seller/commission': typeof AuthenticatedSellerCommissionRoute
  '/_authenticated/seller/coupons': typeof AuthenticatedSellerCouponsRoute
  '/_authenticated/seller/customers': typeof AuthenticatedSellerCustomersRoute
  '/_authenticated/seller/inventory': typeof AuthenticatedSellerInventoryRoute
  '/_authenticated/seller/orders': typeof AuthenticatedSellerOrdersRouteWithChildren
  '/_authenticated/seller/products': typeof AuthenticatedSellerProductsRouteWithChildren
  '/_authenticated/seller/promotions': typeof AuthenticatedSellerPromotionsRoute
  '/_authenticated/seller/reviews': typeof AuthenticatedSellerReviewsRoute
  '/_authenticated/seller/settings': typeof AuthenticatedSellerSettingsRoute
  '/_authenticated/seller/settlements': typeof AuthenticatedSellerSettlementsRoute
  '/_authenticated/seller/shipping': typeof AuthenticatedSellerShippingRoute
  '/_authenticated/seller/staff': typeof AuthenticatedSellerStaffRoute
  '/_authenticated/seller/store': typeof AuthenticatedSellerStoreRoute
  '/_authenticated/seller/support': typeof AuthenticatedSellerSupportRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/sellers/$sellerId': typeof AdminSellersSellerIdRoute
  '/_authenticated/account/orders/$orderId': typeof AuthenticatedAccountOrdersOrderIdRoute
  '/_authenticated/seller/orders/$orderId': typeof AuthenticatedSellerOrdersOrderIdRoute
  '/_authenticated/seller/products/$productId': typeof AuthenticatedSellerProductsProductIdRoute
  '/_authenticated/seller/products/new': typeof AuthenticatedSellerProductsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/become-a-seller'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/help'
    | '/order-success'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/track-order'
    | '/wishlist'
    | '/seller'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/homepage'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/sellers'
    | '/admin/settlements'
    | '/admin/shipping'
    | '/category/$slug'
    | '/product/$slug'
    | '/store/$slug'
    | '/admin/'
    | '/account/orders'
    | '/seller/ai'
    | '/seller/analytics'
    | '/seller/appearance'
    | '/seller/bundles'
    | '/seller/commission'
    | '/seller/coupons'
    | '/seller/customers'
    | '/seller/inventory'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/promotions'
    | '/seller/reviews'
    | '/seller/settings'
    | '/seller/settlements'
    | '/seller/shipping'
    | '/seller/staff'
    | '/seller/store'
    | '/seller/support'
    | '/admin/orders/$orderId'
    | '/admin/sellers/$sellerId'
    | '/account/orders/$orderId'
    | '/seller/orders/$orderId'
    | '/seller/products/$productId'
    | '/seller/products/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/become-a-seller'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/help'
    | '/order-success'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/track-order'
    | '/wishlist'
    | '/seller'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/homepage'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/sellers'
    | '/admin/settlements'
    | '/admin/shipping'
    | '/category/$slug'
    | '/product/$slug'
    | '/store/$slug'
    | '/admin'
    | '/account/orders'
    | '/seller/ai'
    | '/seller/analytics'
    | '/seller/appearance'
    | '/seller/bundles'
    | '/seller/commission'
    | '/seller/coupons'
    | '/seller/customers'
    | '/seller/inventory'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/promotions'
    | '/seller/reviews'
    | '/seller/settings'
    | '/seller/settlements'
    | '/seller/shipping'
    | '/seller/staff'
    | '/seller/store'
    | '/seller/support'
    | '/admin/orders/$orderId'
    | '/admin/sellers/$sellerId'
    | '/account/orders/$orderId'
    | '/seller/orders/$orderId'
    | '/seller/products/$productId'
    | '/seller/products/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/become-a-seller'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/help'
    | '/order-success'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/track-order'
    | '/wishlist'
    | '/_authenticated/seller'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/homepage'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/sellers'
    | '/admin/settlements'
    | '/admin/shipping'
    | '/category/$slug'
    | '/product/$slug'
    | '/store/$slug'
    | '/admin/'
    | '/_authenticated/account/orders'
    | '/_authenticated/seller/ai'
    | '/_authenticated/seller/analytics'
    | '/_authenticated/seller/appearance'
    | '/_authenticated/seller/bundles'
    | '/_authenticated/seller/commission'
    | '/_authenticated/seller/coupons'
    | '/_authenticated/seller/customers'
    | '/_authenticated/seller/inventory'
    | '/_authenticated/seller/orders'
    | '/_authenticated/seller/products'
    | '/_authenticated/seller/promotions'
    | '/_authenticated/seller/reviews'
    | '/_authenticated/seller/settings'
    | '/_authenticated/seller/settlements'
    | '/_authenticated/seller/shipping'
    | '/_authenticated/seller/staff'
    | '/_authenticated/seller/store'
    | '/_authenticated/seller/support'
    | '/admin/orders/$orderId'
    | '/admin/sellers/$sellerId'
    | '/_authenticated/account/orders/$orderId'
    | '/_authenticated/seller/orders/$orderId'
    | '/_authenticated/seller/products/$productId'
    | '/_authenticated/seller/products/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BecomeASellerRoute: typeof BecomeASellerRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  HelpRoute: typeof HelpRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRoute
  TermsRoute: typeof TermsRoute
  TrackOrderRoute: typeof TrackOrderRoute
  WishlistRoute: typeof WishlistRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSellersRoute: typeof AdminSellersRouteWithChildren
  AdminSettlementsRoute: typeof AdminSettlementsRoute
  AdminShippingRoute: typeof AdminShippingRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  StoreSlugRoute: typeof StoreSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-seller': {
      id: '/become-a-seller'
      path: '/become-a-seller'
      fullPath: '/become-a-seller'
      preLoaderRoute: typeof BecomeASellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/seller': {
      id: '/_authenticated/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof AuthenticatedSellerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/admin/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sellers': {
      id: '/admin/sellers'
      path: '/admin/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AdminSellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settlements': {
      id: '/admin/settlements'
      path: '/admin/settlements'
      fullPath: '/admin/settlements'
      preLoaderRoute: typeof AdminSettlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/admin/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/orders': {
      id: '/_authenticated/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AuthenticatedAccountOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seller/ai': {
      id: '/_authenticated/seller/ai'
      path: '/ai'
      fullPath: '/seller/ai'
      preLoaderRoute: typeof AuthenticatedSellerAiRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/analytics': {
      id: '/_authenticated/seller/analytics'
      path: '/analytics'
      fullPath: '/seller/analytics'
      preLoaderRoute: typeof AuthenticatedSellerAnalyticsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/appearance': {
      id: '/_authenticated/seller/appearance'
      path: '/appearance'
      fullPath: '/seller/appearance'
      preLoaderRoute: typeof AuthenticatedSellerAppearanceRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/bundles': {
      id: '/_authenticated/seller/bundles'
      path: '/bundles'
      fullPath: '/seller/bundles'
      preLoaderRoute: typeof AuthenticatedSellerBundlesRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/commission': {
      id: '/_authenticated/seller/commission'
      path: '/commission'
      fullPath: '/seller/commission'
      preLoaderRoute: typeof AuthenticatedSellerCommissionRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/coupons': {
      id: '/_authenticated/seller/coupons'
      path: '/coupons'
      fullPath: '/seller/coupons'
      preLoaderRoute: typeof AuthenticatedSellerCouponsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/customers': {
      id: '/_authenticated/seller/customers'
      path: '/customers'
      fullPath: '/seller/customers'
      preLoaderRoute: typeof AuthenticatedSellerCustomersRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/inventory': {
      id: '/_authenticated/seller/inventory'
      path: '/inventory'
      fullPath: '/seller/inventory'
      preLoaderRoute: typeof AuthenticatedSellerInventoryRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/orders': {
      id: '/_authenticated/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof AuthenticatedSellerOrdersRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/products': {
      id: '/_authenticated/seller/products'
      path: '/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof AuthenticatedSellerProductsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/promotions': {
      id: '/_authenticated/seller/promotions'
      path: '/promotions'
      fullPath: '/seller/promotions'
      preLoaderRoute: typeof AuthenticatedSellerPromotionsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/reviews': {
      id: '/_authenticated/seller/reviews'
      path: '/reviews'
      fullPath: '/seller/reviews'
      preLoaderRoute: typeof AuthenticatedSellerReviewsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/settings': {
      id: '/_authenticated/seller/settings'
      path: '/settings'
      fullPath: '/seller/settings'
      preLoaderRoute: typeof AuthenticatedSellerSettingsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/settlements': {
      id: '/_authenticated/seller/settlements'
      path: '/settlements'
      fullPath: '/seller/settlements'
      preLoaderRoute: typeof AuthenticatedSellerSettlementsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/shipping': {
      id: '/_authenticated/seller/shipping'
      path: '/shipping'
      fullPath: '/seller/shipping'
      preLoaderRoute: typeof AuthenticatedSellerShippingRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/staff': {
      id: '/_authenticated/seller/staff'
      path: '/staff'
      fullPath: '/seller/staff'
      preLoaderRoute: typeof AuthenticatedSellerStaffRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/store': {
      id: '/_authenticated/seller/store'
      path: '/store'
      fullPath: '/seller/store'
      preLoaderRoute: typeof AuthenticatedSellerStoreRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/support': {
      id: '/_authenticated/seller/support'
      path: '/support'
      fullPath: '/seller/support'
      preLoaderRoute: typeof AuthenticatedSellerSupportRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/sellers/$sellerId': {
      id: '/admin/sellers/$sellerId'
      path: '/$sellerId'
      fullPath: '/admin/sellers/$sellerId'
      preLoaderRoute: typeof AdminSellersSellerIdRouteImport
      parentRoute: typeof AdminSellersRoute
    }
    '/_authenticated/account/orders/$orderId': {
      id: '/_authenticated/account/orders/$orderId'
      path: '/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedAccountOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedAccountOrdersRoute
    }
    '/_authenticated/seller/orders/$orderId': {
      id: '/_authenticated/seller/orders/$orderId'
      path: '/$orderId'
      fullPath: '/seller/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedSellerOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedSellerOrdersRoute
    }
    '/_authenticated/seller/products/$productId': {
      id: '/_authenticated/seller/products/$productId'
      path: '/$productId'
      fullPath: '/seller/products/$productId'
      preLoaderRoute: typeof AuthenticatedSellerProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedSellerProductsRoute
    }
    '/_authenticated/seller/products/new': {
      id: '/_authenticated/seller/products/new'
      path: '/new'
      fullPath: '/seller/products/new'
      preLoaderRoute: typeof AuthenticatedSellerProductsNewRouteImport
      parentRoute: typeof AuthenticatedSellerProductsRoute
    }
  }
}

interface AuthenticatedSellerOrdersRouteChildren {
  AuthenticatedSellerOrdersOrderIdRoute: typeof AuthenticatedSellerOrdersOrderIdRoute
}

const AuthenticatedSellerOrdersRouteChildren: AuthenticatedSellerOrdersRouteChildren =
  {
    AuthenticatedSellerOrdersOrderIdRoute:
      AuthenticatedSellerOrdersOrderIdRoute,
  }

const AuthenticatedSellerOrdersRouteWithChildren =
  AuthenticatedSellerOrdersRoute._addFileChildren(
    AuthenticatedSellerOrdersRouteChildren,
  )

interface AuthenticatedSellerProductsRouteChildren {
  AuthenticatedSellerProductsProductIdRoute: typeof AuthenticatedSellerProductsProductIdRoute
  AuthenticatedSellerProductsNewRoute: typeof AuthenticatedSellerProductsNewRoute
}

const AuthenticatedSellerProductsRouteChildren: AuthenticatedSellerProductsRouteChildren =
  {
    AuthenticatedSellerProductsProductIdRoute:
      AuthenticatedSellerProductsProductIdRoute,
    AuthenticatedSellerProductsNewRoute: AuthenticatedSellerProductsNewRoute,
  }

const AuthenticatedSellerProductsRouteWithChildren =
  AuthenticatedSellerProductsRoute._addFileChildren(
    AuthenticatedSellerProductsRouteChildren,
  )

interface AuthenticatedSellerRouteChildren {
  AuthenticatedSellerAiRoute: typeof AuthenticatedSellerAiRoute
  AuthenticatedSellerAnalyticsRoute: typeof AuthenticatedSellerAnalyticsRoute
  AuthenticatedSellerAppearanceRoute: typeof AuthenticatedSellerAppearanceRoute
  AuthenticatedSellerBundlesRoute: typeof AuthenticatedSellerBundlesRoute
  AuthenticatedSellerCommissionRoute: typeof AuthenticatedSellerCommissionRoute
  AuthenticatedSellerCouponsRoute: typeof AuthenticatedSellerCouponsRoute
  AuthenticatedSellerCustomersRoute: typeof AuthenticatedSellerCustomersRoute
  AuthenticatedSellerInventoryRoute: typeof AuthenticatedSellerInventoryRoute
  AuthenticatedSellerOrdersRoute: typeof AuthenticatedSellerOrdersRouteWithChildren
  AuthenticatedSellerProductsRoute: typeof AuthenticatedSellerProductsRouteWithChildren
  AuthenticatedSellerPromotionsRoute: typeof AuthenticatedSellerPromotionsRoute
  AuthenticatedSellerReviewsRoute: typeof AuthenticatedSellerReviewsRoute
  AuthenticatedSellerSettingsRoute: typeof AuthenticatedSellerSettingsRoute
  AuthenticatedSellerSettlementsRoute: typeof AuthenticatedSellerSettlementsRoute
  AuthenticatedSellerShippingRoute: typeof AuthenticatedSellerShippingRoute
  AuthenticatedSellerStaffRoute: typeof AuthenticatedSellerStaffRoute
  AuthenticatedSellerStoreRoute: typeof AuthenticatedSellerStoreRoute
  AuthenticatedSellerSupportRoute: typeof AuthenticatedSellerSupportRoute
}

const AuthenticatedSellerRouteChildren: AuthenticatedSellerRouteChildren = {
  AuthenticatedSellerAiRoute: AuthenticatedSellerAiRoute,
  AuthenticatedSellerAnalyticsRoute: AuthenticatedSellerAnalyticsRoute,
  AuthenticatedSellerAppearanceRoute: AuthenticatedSellerAppearanceRoute,
  AuthenticatedSellerBundlesRoute: AuthenticatedSellerBundlesRoute,
  AuthenticatedSellerCommissionRoute: AuthenticatedSellerCommissionRoute,
  AuthenticatedSellerCouponsRoute: AuthenticatedSellerCouponsRoute,
  AuthenticatedSellerCustomersRoute: AuthenticatedSellerCustomersRoute,
  AuthenticatedSellerInventoryRoute: AuthenticatedSellerInventoryRoute,
  AuthenticatedSellerOrdersRoute: AuthenticatedSellerOrdersRouteWithChildren,
  AuthenticatedSellerProductsRoute:
    AuthenticatedSellerProductsRouteWithChildren,
  AuthenticatedSellerPromotionsRoute: AuthenticatedSellerPromotionsRoute,
  AuthenticatedSellerReviewsRoute: AuthenticatedSellerReviewsRoute,
  AuthenticatedSellerSettingsRoute: AuthenticatedSellerSettingsRoute,
  AuthenticatedSellerSettlementsRoute: AuthenticatedSellerSettlementsRoute,
  AuthenticatedSellerShippingRoute: AuthenticatedSellerShippingRoute,
  AuthenticatedSellerStaffRoute: AuthenticatedSellerStaffRoute,
  AuthenticatedSellerStoreRoute: AuthenticatedSellerStoreRoute,
  AuthenticatedSellerSupportRoute: AuthenticatedSellerSupportRoute,
}

const AuthenticatedSellerRouteWithChildren =
  AuthenticatedSellerRoute._addFileChildren(AuthenticatedSellerRouteChildren)

interface AuthenticatedAccountOrdersRouteChildren {
  AuthenticatedAccountOrdersOrderIdRoute: typeof AuthenticatedAccountOrdersOrderIdRoute
}

const AuthenticatedAccountOrdersRouteChildren: AuthenticatedAccountOrdersRouteChildren =
  {
    AuthenticatedAccountOrdersOrderIdRoute:
      AuthenticatedAccountOrdersOrderIdRoute,
  }

const AuthenticatedAccountOrdersRouteWithChildren =
  AuthenticatedAccountOrdersRoute._addFileChildren(
    AuthenticatedAccountOrdersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSellerRoute: typeof AuthenticatedSellerRouteWithChildren
  AuthenticatedAccountOrdersRoute: typeof AuthenticatedAccountOrdersRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSellerRoute: AuthenticatedSellerRouteWithChildren,
  AuthenticatedAccountOrdersRoute: AuthenticatedAccountOrdersRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminOrdersRouteChildren {
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminSellersRouteChildren {
  AdminSellersSellerIdRoute: typeof AdminSellersSellerIdRoute
}

const AdminSellersRouteChildren: AdminSellersRouteChildren = {
  AdminSellersSellerIdRoute: AdminSellersSellerIdRoute,
}

const AdminSellersRouteWithChildren = AdminSellersRoute._addFileChildren(
  AdminSellersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BecomeASellerRoute: BecomeASellerRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  HelpRoute: HelpRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRoute,
  TermsRoute: TermsRoute,
  TrackOrderRoute: TrackOrderRoute,
  WishlistRoute: WishlistRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminProductsRoute: AdminProductsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSellersRoute: AdminSellersRouteWithChildren,
  AdminSettlementsRoute: AdminSettlementsRoute,
  AdminShippingRoute: AdminShippingRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  StoreSlugRoute: StoreSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
