/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as BecomeASellerRouteImport } from './routes/become-a-seller'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as AuthenticatedAccountOrdersRouteImport } from './routes/_authenticated/account.orders'
import { Route as AuthenticatedSellerOrdersRouteImport } from './routes/_authenticated/seller.orders'
import { Route as AuthenticatedSellerRouteImport } from './routes/_authenticated/seller'
import { Route as AuthenticatedSellerProductsRouteImport } from './routes/_authenticated/seller.products'
import { Route as AuthenticatedSellerStaffRouteImport } from './routes/_authenticated/seller.staff'
import { Route as AuthenticatedAccountOrdersOrderIdRouteImport } from './routes/_authenticated/account.orders.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeASellerRoute = BecomeASellerRouteImport.update({
  id: '/become-a-seller',
  path: '/become-a-seller',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountOrdersRoute =
  AuthenticatedAccountOrdersRouteImport.update({
    id: '/account/orders',
    path: '/account/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSellerRoute = AuthenticatedSellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellerOrdersRoute =
  AuthenticatedSellerOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerProductsRoute = AuthenticatedSellerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedSellerRoute,
} as any)
const AuthenticatedSellerStaffRoute = AuthenticatedSellerStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedSellerRoute,
} as any)
const AuthenticatedAccountOrdersOrderIdRoute =
  AuthenticatedAccountOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedAccountOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/': typeof AdminRoute
  '/become-a-seller': typeof BecomeASellerRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/order-success': typeof OrderSuccessRoute
  '/shop': typeof ShopRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRouteWithChildren
  '/seller/orders': typeof AuthenticatedSellerOrdersRoute
  '/seller/products': typeof AuthenticatedSellerProductsRoute
  '/seller/staff': typeof AuthenticatedSellerStaffRoute
  '/account/orders/$orderId': typeof AuthenticatedAccountOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/': typeof AdminRoute
  '/become-a-seller': typeof BecomeASellerRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/order-success': typeof OrderSuccessRoute
  '/shop': typeof ShopRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRouteWithChildren
  '/seller/orders': typeof AuthenticatedSellerOrdersRoute
  '/seller/products': typeof AuthenticatedSellerProductsRoute
  '/seller/staff': typeof AuthenticatedSellerStaffRoute
  '/account/orders/$orderId': typeof AuthenticatedAccountOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/': typeof AdminRoute
  '/become-a-seller': typeof BecomeASellerRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/order-success': typeof OrderSuccessRoute
  '/shop': typeof ShopRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/_authenticated/account/orders': typeof AuthenticatedAccountOrdersRouteWithChildren
  '/_authenticated/seller': typeof AuthenticatedSellerRouteWithChildren
  '/_authenticated/seller/orders': typeof AuthenticatedSellerOrdersRoute
  '/_authenticated/seller/products': typeof AuthenticatedSellerProductsRoute
  '/_authenticated/seller/staff': typeof AuthenticatedSellerStaffRoute
  '/_authenticated/account/orders/$orderId': typeof AuthenticatedAccountOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/'
    | '/auth'
    | '/admin/'
    | '/become-a-seller'
    | '/cart'
    | '/checkout'
    | '/order-success'
    | '/shop'
    | '/track-order'
    | '/wishlist'
    | '/category/$slug'
    | '/product/$slug'
    | '/store/$slug'
    | '/account/orders'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/staff'
    | '/account/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/become-a-seller'
    | '/cart'
    | '/checkout'
    | '/order-success'
    | '/shop'
    | '/track-order'
    | '/wishlist'
    | '/category/$slug'
    | '/product/$slug'
    | '/store/$slug'
    | '/account/orders'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/staff'
    | '/account/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/become-a-seller'
    | '/cart'
    | '/checkout'
    | '/order-success'
    | '/shop'
    | '/track-order'
    | '/wishlist'
    | '/category/$slug'
    | '/product/$slug'
    | '/store/$slug'
    | '/_authenticated/account/orders'
    | '/_authenticated/seller/orders'
    | '/_authenticated/account/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BecomeASellerRoute: typeof BecomeASellerRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  ShopRoute: typeof ShopRoute
  TrackOrderRoute: typeof TrackOrderRoute
  WishlistRoute: typeof WishlistRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  StoreSlugRoute: typeof StoreSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-seller': {
      id: '/become-a-seller'
      path: '/become-a-seller'
      fullPath: '/become-a-seller'
      preLoaderRoute: typeof BecomeASellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/orders': {
      id: '/_authenticated/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AuthenticatedAccountOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seller/orders': {
      id: '/_authenticated/seller/orders'
      path: '/seller/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof AuthenticatedSellerOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/orders/$orderId': {
      id: '/_authenticated/account/orders/$orderId'
      path: '/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedAccountOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedAccountOrdersRoute
    }
  }
}

interface AuthenticatedAccountOrdersRouteChildren {
  AuthenticatedAccountOrdersOrderIdRoute: typeof AuthenticatedAccountOrdersOrderIdRoute
}

const AuthenticatedAccountOrdersRouteChildren: AuthenticatedAccountOrdersRouteChildren =
  {
    AuthenticatedAccountOrdersOrderIdRoute:
      AuthenticatedAccountOrdersOrderIdRoute,
  }

const AuthenticatedAccountOrdersRouteWithChildren =
  AuthenticatedAccountOrdersRoute._addFileChildren(
    AuthenticatedAccountOrdersRouteChildren,
  )

interface AuthenticatedSellerRouteChildren {
  AuthenticatedSellerOrdersRoute: typeof AuthenticatedSellerOrdersRoute
  AuthenticatedSellerProductsRoute: typeof AuthenticatedSellerProductsRoute
  AuthenticatedSellerStaffRoute: typeof AuthenticatedSellerStaffRoute
}

const AuthenticatedSellerRouteChildren: AuthenticatedSellerRouteChildren = {
  AuthenticatedSellerOrdersRoute: AuthenticatedSellerOrdersRoute,
  AuthenticatedSellerProductsRoute: AuthenticatedSellerProductsRoute,
  AuthenticatedSellerStaffRoute: AuthenticatedSellerStaffRoute,
}

const AuthenticatedSellerRouteWithChildren = AuthenticatedSellerRoute._addFileChildren(AuthenticatedSellerRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountOrdersRoute: typeof AuthenticatedAccountOrdersRouteWithChildren
  AuthenticatedSellerRoute: typeof AuthenticatedSellerRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountOrdersRoute: AuthenticatedAccountOrdersRouteWithChildren,
  AuthenticatedSellerRoute: AuthenticatedSellerRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AdminRoute: AdminRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BecomeASellerRoute: BecomeASellerRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  ShopRoute: ShopRoute,
  TrackOrderRoute: TrackOrderRoute,
  WishlistRoute: WishlistRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  StoreSlugRoute: StoreSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
