-- MODALIA FINALIZATION — Phase 3/8 (Super Admin Operating System)
--
-- Real commune data for all 58 Algerian wilayas (1,541 communes).
-- Source: DZBuild dzship open dataset (data/communes.json) — free to use,
-- no attribution required. Each commune carries its official French name
-- and Arabic name as published in that dataset.
--
-- Replaces the placeholder "Centre / Autre" rows seeded earlier. Commune
-- codes are synthetic but stable: '<wilaya2>-<seq3>' (e.g. '16-001').
-- Idempotent: safe to re-run (upserts by code).

BEGIN;

-- Remove placeholder communes seeded by earlier migrations.
DELETE FROM public.communes WHERE code ~ '^[0-9]{2}-000$';

WITH src (wcode, seq, ar, fr, en) AS (
  VALUES
    ('01','001','أدرار','Adrar','Adrar'),
    ('01','002','اقبلي','Akabli','Akabli'),
    ('01','003','أولف','Aoulef','Aoulef'),
    ('01','004','بودة','Bouda','Bouda'),
    ('01','005','فنوغيل','Fenoughil','Fenoughil'),
    ('01','006','إن زغمير','In Zghmir','In Zghmir'),
    ('01','007','أولاد أحمد تيمي','Ouled Ahmed Timmi','Ouled Ahmed Timmi'),
    ('01','008','رقان','Reggane','Reggane'),
    ('01','009','سالي','Sali','Sali'),
    ('01','010','السبع','Sebaa','Sebaa'),
    ('01','011','تامنطيط','Tamantit','Tamantit'),
    ('01','012','تامست','Tamest','Tamest'),
    ('01','013','تيمقتن','Timekten','Timekten'),
    ('01','014','تيت','Tit','Tit'),
    ('01','015','تسابيت','Tsabit','Tsabit'),
    ('01','016','زاوية كنتة','Zaouiet Kounta','Zaouiet Kounta'),
    ('02','001','أبو الحسن','Abou El Hassane','Abou El Hassane'),
    ('02','002','عين مران','Ain Merane','Ain Merane'),
    ('02','003','بنايرية','Benairia','Benairia'),
    ('02','004','بني بوعتاب','Beni Bouattab','Beni Bouattab'),
    ('02','005','بني حواء','Beni Haoua','Beni Haoua'),
    ('02','006','بني راشد','Beni Rached','Beni Rached'),
    ('02','007','بوقادير','Boukadir','Boukadir'),
    ('02','008','بوزغاية','Bouzeghaia','Bouzeghaia'),
    ('02','009','بريرة','Breira','Breira'),
    ('02','010','الشطية','Chettia','Chettia'),
    ('02','011','الشلف','Chlef','Chlef'),
    ('02','012','الظهرة','Dahra','Dahra'),
    ('02','013','الحجاج','El Hadjadj','El Hadjadj'),
    ('02','014','الكريمية','El Karimia','El Karimia'),
    ('02','015','المرسى','El Marsa','El Marsa'),
    ('02','016','حرشون','Harchoun','Harchoun'),
    ('02','017','الهرانفة','Herenfa','Herenfa'),
    ('02','018','الأبيض مجاجة','Labiod Medjadja','Labiod Medjadja'),
    ('02','019','مصدق','Moussadek','Moussadek'),
    ('02','020','وادي الفضة','Oued Fodda','Oued Fodda'),
    ('02','021','وادي قوسين','Oued Goussine','Oued Goussine'),
    ('02','022','وادي سلي','Oued Sly','Oued Sly'),
    ('02','023','أولاد عباس','Ouled Abbes','Ouled Abbes'),
    ('02','024','أولاد بن عبد القادر','Ouled Ben Abdelkader','Ouled Ben Abdelkader'),
    ('02','025','أولاد فارس','Ouled Fares','Ouled Fares'),
    ('02','026','أم الدروع','Oum Drou','Oum Drou'),
    ('02','027','سنجاس','Sendjas','Sendjas'),
    ('02','028','سيدي عبد الرحمن','Sidi Abderrahmane','Sidi Abderrahmane'),
    ('02','029','سيدي عكاشة','Sidi Akkacha','Sidi Akkacha'),
    ('02','030','الصبحة','Sobha','Sobha'),
    ('02','031','تاجنة','Tadjena','Tadjena'),
    ('02','032','تلعصة','Talassa','Talassa'),
    ('02','033','تاوقريت','Taougrit','Taougrit'),
    ('02','034','تنس','Tenes','Tenes'),
    ('02','035','الزبوجة','Zeboudja','Zeboudja'),
    ('03','001','أفلو','Aflou','Aflou'),
    ('03','002','عين ماضي','Ain Madhi','Ain Madhi'),
    ('03','003','عين سيدي علي','Ain Sidi Ali','Ain Sidi Ali'),
    ('03','004','بن ناصر بن شهرة','Benacer Benchohra','Benacer Benchohra'),
    ('03','005','بريدة','Brida','Brida'),
    ('03','006','العسافية','El Assafia','El Assafia'),
    ('03','007','البيضاء','El Beidha','El Beidha'),
    ('03','008','الغيشة','El Ghicha','El Ghicha'),
    ('03','009','الحويطة','El Haouaita','El Haouaita'),
    ('03','010','قلتة سيدي سعد','Gueltat Sidi Saad','Gueltat Sidi Saad'),
    ('03','011','الحاج مشري','Hadj Mechri','Hadj Mechri'),
    ('03','012','حاسي الدلاعة','Hassi Delaa','Hassi Delaa'),
    ('03','013','حاسي الرمل','Hassi R''Mel','Hassi R''Mel'),
    ('03','014','الخنق','Kheneg','Kheneg'),
    ('03','015','قصر الحيران','Ksar El Hirane','Ksar El Hirane'),
    ('03','016','الأغواط','Laghouat','Laghouat'),
    ('03','017','وادي مزي','Oued M''Zi','Oued M''Zi'),
    ('03','018','وادي مرة','Oued Morra','Oued Morra'),
    ('03','019','سبقاق','Sebgag','Sebgag'),
    ('03','020','سيدي بوزيد','Sidi Bouzid','Sidi Bouzid'),
    ('03','021','سيدي مخلوف','Sidi Makhlouf','Sidi Makhlouf'),
    ('03','022','تاجموت','Tadjemout','Tadjemout'),
    ('03','023','تاجرونة','Tadjrouna','Tadjrouna'),
    ('03','024','تاويالة','Taouiala','Taouiala'),
    ('04','001','عين ببوش','Ain Babouche','Ain Babouche'),
    ('04','002','عين البيضاء','Ain Beida','Ain Beida'),
    ('04','003','عين الديس','Ain Diss','Ain Diss'),
    ('04','004','عين فكرون','Ain Fekroun','Ain Fekroun'),
    ('04','005','عين كرشة','Ain Kercha','Ain Kercha'),
    ('04','006','عين الزيتون','Ain Zitoun','Ain Zitoun'),
    ('04','007','عين مليلة','Aïn M''lila','Aïn M''lila'),
    ('04','008','بحير الشرقي','Behir Chergui','Behir Chergui'),
    ('04','009','بريش','Berriche','Berriche'),
    ('04','010','بئر الشهداء','Bir Chouhada','Bir Chouhada'),
    ('04','011','الضلعة','Dhalaa','Dhalaa'),
    ('04','012','العامرية','El Amiria','El Amiria'),
    ('04','013','البلالة','El Belala','El Belala'),
    ('04','014','الجازية','El Djazia','El Djazia'),
    ('04','015','الفجوج بوغرارة سعودي','El Fedjoudj Boughrara Sa','El Fedjoudj Boughrara Sa'),
    ('04','016','الحرملية','El Harmilia','El Harmilia'),
    ('04','017','فكيرينة','Fkirina','Fkirina'),
    ('04','018','هنشير تومغني','Hanchir Toumghani','Hanchir Toumghani'),
    ('04','019','قصر الصباحي','Ksar Sbahi','Ksar Sbahi'),
    ('04','020','مسكيانة','Meskiana','Meskiana'),
    ('04','021','وادي نيني','Oued Nini','Oued Nini'),
    ('04','022','أولاد قاسم','Ouled Gacem','Ouled Gacem'),
    ('04','023','أولاد حملة','Ouled Hamla','Ouled Hamla'),
    ('04','024','أولاد زواي','Ouled Zouai','Ouled Zouai'),
    ('04','025','أم البواقي','Oum El Bouaghi','Oum El Bouaghi'),
    ('04','026','الرحية','Rahia','Rahia'),
    ('04','027','سيقوس','Sigus','Sigus'),
    ('04','028','سوق نعمان','Souk Naamane','Souk Naamane'),
    ('04','029','الزرق','Zorg','Zorg'),
    ('05','001','عين جاسر','Ain Djasser','Ain Djasser'),
    ('05','002','عين التوتة','Ain Touta','Ain Touta'),
    ('05','003','عين ياقوت','Ain Yagout','Ain Yagout'),
    ('05','004','أريس','Arris','Arris'),
    ('05','005','عزيل عبد القادر','Azil Abedelkader','Azil Abedelkader'),
    ('05','006','بريكة','Barika','Barika'),
    ('05','007','باتنة','Batna','Batna'),
    ('05','008','بني فضالة الحقانية','Beni Foudhala El Hakania','Beni Foudhala El Hakania'),
    ('05','009','بيطام','Bitam','Bitam'),
    ('05','010','بولهيلات','Boulhilat','Boulhilat'),
    ('05','011','بومقر','Boumagueur','Boumagueur'),
    ('05','012','بومية','Boumia','Boumia'),
    ('05','013','بوزينة','Bouzina','Bouzina'),
    ('05','014','الشمرة','Chemora','Chemora'),
    ('05','015','شير','Chir','Chir'),
    ('05','016','جرمة','Djerma','Djerma'),
    ('05','017','الجزار','Djezzar','Djezzar'),
    ('05','018','الحاسي','El Hassi','El Hassi'),
    ('05','019','المعذر','El Madher','El Madher'),
    ('05','020','فسديس','Fesdis','Fesdis'),
    ('05','021','فم الطوب','Foum Toub','Foum Toub'),
    ('05','022','غسيرة','Ghassira','Ghassira'),
    ('05','023','القصبات','Gosbat','Gosbat'),
    ('05','024','القيقبة','Guigba','Guigba'),
    ('05','025','حيدوسة','Hidoussa','Hidoussa'),
    ('05','026','إشمول','Ichemoul','Ichemoul'),
    ('05','027','إينوغيسن','Inoughissen','Inoughissen'),
    ('05','028','كيمل','Kimmel','Kimmel'),
    ('05','029','قصر بلزمة','Ksar Bellezma','Ksar Bellezma'),
    ('05','030','لارباع','Larbaa','Larbaa'),
    ('05','031','لازرو','Lazrou','Lazrou'),
    ('05','032','لمسان','Lemcene','Lemcene'),
    ('05','033','إمدوكل','M Doukal','M Doukal'),
    ('05','034','معافة','Maafa','Maafa'),
    ('05','035','منعة','Menaa','Menaa'),
    ('05','036','مروانة','Merouana','Merouana'),
    ('05','037','نقاوس','N Gaous','N Gaous'),
    ('05','038','وادي الشعبة','Oued Chaaba','Oued Chaaba'),
    ('05','039','وادي الماء','Oued El Ma','Oued El Ma'),
    ('05','040','وادي الطاقة','Oued Taga','Oued Taga'),
    ('05','041','أولاد عمار','Ouled Ammar','Ouled Ammar'),
    ('05','042','أولاد عوف','Ouled Aouf','Ouled Aouf'),
    ('05','043','أولاد فاضل','Ouled Fadel','Ouled Fadel'),
    ('05','044','أولاد سلام','Ouled Sellem','Ouled Sellem'),
    ('05','045','أولاد سي سليمان','Ouled Si Slimane','Ouled Si Slimane'),
    ('05','046','عيون العصافير','Ouyoun El Assafir','Ouyoun El Assafir'),
    ('05','047','الرحبات','Rahbat','Rahbat'),
    ('05','048','رأس العيون','Ras El Aioun','Ras El Aioun'),
    ('05','049','سفيان','Sefiane','Sefiane'),
    ('05','050','سقانة','Seggana','Seggana'),
    ('05','051','سريانة','Seriana','Seriana'),
    ('05','052','تكوت','T Kout','T Kout'),
    ('05','053','تالخمت','Talkhamt','Talkhamt'),
    ('05','054','تاكسلانت','Taxlent','Taxlent'),
    ('05','055','تازولت','Tazoult','Tazoult'),
    ('05','056','ثنية العابد','Teniet El Abed','Teniet El Abed'),
    ('05','057','تيغانمين','Tighanimine','Tighanimine'),
    ('05','058','تغرغار','Tigharghar','Tigharghar'),
    ('05','059','تيلاطو','Tilatou','Tilatou'),
    ('05','060','تيمقاد','Timgad','Timgad'),
    ('05','061','زانة البيضاء','Zanet El Beida','Zanet El Beida'),
    ('06','001','أدكار','Adekar','Adekar'),
    ('06','002','أيت إسماعيل','Ait-Smail','Ait-Smail'),
    ('06','003','أقبو','Akbou','Akbou'),
    ('06','004','أكفادو','Akfadou','Akfadou'),
    ('06','005','أمالو','Amalou','Amalou'),
    ('06','006','أميزور','Amizour','Amizour'),
    ('06','007','أوقاس','Aokas','Aokas'),
    ('06','008','أيت رزين','Aït R''zine','Aït R''zine'),
    ('06','009','برباشة','Barbacha','Barbacha'),
    ('06','010','بجاية','Bejaia','Bejaia'),
    ('06','011','بني جليل','Beni Djellil','Beni Djellil'),
    ('06','012','بني كسيلة','Beni K''sila','Beni K''sila'),
    ('06','013','بني مليكش','Beni-Mallikeche','Beni-Mallikeche'),
    ('06','014','بني معوش','Benimaouche','Benimaouche'),
    ('06','015','بو جليل','Boudjellil','Boudjellil'),
    ('06','016','بوحمزة','Bouhamza','Bouhamza'),
    ('06','017','بوخليفة','Boukhelifa','Boukhelifa'),
    ('06','018','شلاطة','Chellata','Chellata'),
    ('06','019','شميني','Chemini','Chemini'),
    ('06','020','درقينة','Darguina','Darguina'),
    ('06','021','ذراع القايد','Dra El Caid','Dra El Caid'),
    ('06','022','القصر','El Kseur','El Kseur'),
    ('06','023','فناية الماثن','Fenaia Il Maten','Fenaia Il Maten'),
    ('06','024','فرعون','Feraoun','Feraoun'),
    ('06','025','إغيل علي','Ighil-Ali','Ighil-Ali'),
    ('06','026','اغرم','Ighram','Ighram'),
    ('06','027','كنديرة','Kendira','Kendira'),
    ('06','028','خراطة','Kherrata','Kherrata'),
    ('06','029','الفلاي','Leflaye','Leflaye'),
    ('06','030','مسيسنة','M''cisna','M''cisna'),
    ('06','031','مالبو','Melbou','Melbou'),
    ('06','032','وادي غير','Oued Ghir','Oued Ghir'),
    ('06','033','أوزلاقن','Ouzellaguen','Ouzellaguen'),
    ('06','034','صدوق','Seddouk','Seddouk'),
    ('06','035','سيدي عياد','Sidi Ayad','Sidi Ayad'),
    ('06','036','سيدي عيش','Sidi-Aich','Sidi-Aich'),
    ('06','037','سمعون','Smaoun','Smaoun'),
    ('06','038','سوق لإثنين','Souk El Tenine','Souk El Tenine'),
    ('06','039','سوق اوفلا','Souk Oufella','Souk Oufella'),
    ('06','040','تالة حمزة','Tala Hamza','Tala Hamza'),
    ('06','041','تامقرة','Tamokra','Tamokra'),
    ('06','042','تامريجت','Tamridjet','Tamridjet'),
    ('06','043','تاوريرت إغيل','Taourit Ighil','Taourit Ighil'),
    ('06','044','تاسكريوت','Taskriout','Taskriout'),
    ('06','045','تازمالت','Tazmalt','Tazmalt'),
    ('06','046','طيبان','Tibane','Tibane'),
    ('06','047','تيشي','Tichy','Tichy'),
    ('06','048','تيفرة','Tifra','Tifra'),
    ('06','049','تيمزريت','Timezrit','Timezrit'),
    ('06','050','تينبدار','Tinebdar','Tinebdar'),
    ('06','051','تيزي نبربر','Tizi N''Berber','Tizi N''Berber'),
    ('06','052','توجة','Toudja','Toudja'),
    ('07','001','عين الناقة','Ain Naga','Ain Naga'),
    ('07','002','عين زعطوط','Ain Zaatout','Ain Zaatout'),
    ('07','003','بسكرة','Biskra','Biskra'),
    ('07','004','برج بن عزوز','Bordj Ben Azzouz','Bordj Ben Azzouz'),
    ('07','005','بوشقرون','Bouchakroun','Bouchakroun'),
    ('07','006','برانيس','Branis','Branis'),
    ('07','007','شتمة','Chetma','Chetma'),
    ('07','008','جمورة','Djemorah','Djemorah'),
    ('07','009','الفيض','El Feidh','El Feidh'),
    ('07','010','الغروس','El Ghrous','El Ghrous'),
    ('07','011','الحاجب','El Hadjab','El Hadjab'),
    ('07','012','الحوش','El Haouch','El Haouch'),
    ('07','013','القنطرة','El Kantara','El Kantara'),
    ('07','014','الوطاية','El Outaya','El Outaya'),
    ('07','015','فوغالة','Foughala','Foughala'),
    ('07','016','خنقة سيدي ناجي','Khenguet Sidi Nadji','Khenguet Sidi Nadji'),
    ('07','017','ليشانة','Lichana','Lichana'),
    ('07','018','ليوة','Lioua','Lioua'),
    ('07','019','مشونش','M''Chouneche','M''Chouneche'),
    ('07','020','مليلي','M''Lili','M''Lili'),
    ('07','021','مخادمة','Mekhadma','Mekhadma'),
    ('07','022','المزيرعة','Meziraa','Meziraa'),
    ('07','023','أوماش','Oumache','Oumache'),
    ('07','024','أورلال','Ourlal','Ourlal'),
    ('07','025','سيدي عقبة','Sidi Okba','Sidi Okba'),
    ('07','026','طولقة','Tolga','Tolga'),
    ('07','027','زريبة الوادي','Zeribet El Oued','Zeribet El Oued'),
    ('08','001','العبادلة','Abadla','Abadla'),
    ('08','002','بشار','Bechar','Bechar'),
    ('08','003','بني ونيف','Beni-Ounif','Beni-Ounif'),
    ('08','004','بوكايس','Boukais','Boukais'),
    ('08','005','عرق فراج','Erg-Ferradj','Erg-Ferradj'),
    ('08','006','القنادسة','Kenadsa','Kenadsa'),
    ('08','007','لحمر','Lahmar','Lahmar'),
    ('08','008','مشرع هواري بومدين','Machraa-Houari-Boumediene','Machraa-Houari-Boumediene'),
    ('08','009','المريجة','Meridja','Meridja'),
    ('08','010','موغل','Mogheul','Mogheul'),
    ('08','011','تاغيت','Taghit','Taghit'),
    ('09','001','عين الرمانة','Ain Romana','Ain Romana'),
    ('09','002','بني مراد','Beni Mered','Beni Mered'),
    ('09','003','بني تامو','Beni-Tamou','Beni-Tamou'),
    ('09','004','بن خليل','Benkhelil','Benkhelil'),
    ('09','005','البليدة','Blida','Blida'),
    ('09','006','بوعرفة','Bouarfa','Bouarfa'),
    ('09','007','بوفاريك','Boufarik','Boufarik'),
    ('09','008','بوقرة','Bougara','Bougara'),
    ('09','009','بوعينان','Bouinan','Bouinan'),
    ('09','010','الشبلي','Chebli','Chebli'),
    ('09','011','الشفة','Chiffa','Chiffa'),
    ('09','012','الشريعة','Chrea','Chrea'),
    ('09','013','جبابرة','Djebabra','Djebabra'),
    ('09','014','العفرون','El-Affroun','El-Affroun'),
    ('09','015','قرواو','Guerrouaou','Guerrouaou'),
    ('09','016','حمام ملوان','Hammam Elouane','Hammam Elouane'),
    ('09','017','الأربعاء','Larbâa','Larbâa'),
    ('09','018','مفتاح','Meftah','Meftah'),
    ('09','019','موزاية','Mouzaia','Mouzaia'),
    ('09','020','وادي جر','Oued Djer','Oued Djer'),
    ('09','021','وادي العلايق','Oued El Alleug','Oued El Alleug'),
    ('09','022','اولاد سلامة','Ouled Slama','Ouled Slama'),
    ('09','023','أولاد يعيش','Ouled Yaïch','Ouled Yaïch'),
    ('09','024','صوحان','Souhane','Souhane'),
    ('09','025','الصومعة','Soumaa','Soumaa'),
    ('10','001','أغبالو','Aghbalou','Aghbalou'),
    ('10','002','أهل القصر','Ahl El Ksar','Ahl El Ksar'),
    ('10','003','عين الحجر','Ain El Hadjar','Ain El Hadjar'),
    ('10','004','عين العلوي','Ain Laloui','Ain Laloui'),
    ('10','005','عين الترك','Ain Turk','Ain Turk'),
    ('10','006','عين بسام','Ain-Bessem','Ain-Bessem'),
    ('10','007','أيت لعزيز','Ait Laaziz','Ait Laaziz'),
    ('10','008','أعمر','Aomar','Aomar'),
    ('10','009','آث  منصور','Ath Mansour','Ath Mansour'),
    ('10','010','بشلول','Bechloul','Bechloul'),
    ('10','011','بئر غبالو','Bir Ghbalou','Bir Ghbalou'),
    ('10','012','برج أوخريص','Bordj Okhriss','Bordj Okhriss'),
    ('10','013','بودربالة','Bouderbala','Bouderbala'),
    ('10','014','البويرة','Bouira','Bouira'),
    ('10','015','بوكرم','Boukram','Boukram'),
    ('10','016','شرفة','Chorfa','Chorfa'),
    ('10','017','الدشمية','Dechmia','Dechmia'),
    ('10','018','ديرة','Dirah','Dirah'),
    ('10','019','جباحية','Djebahia','Djebahia'),
    ('10','020','العجيبة','El Adjiba','El Adjiba'),
    ('10','021','الأسنام','El Asnam','El Asnam'),
    ('10','022','الهاشمية','El Hachimia','El Hachimia'),
    ('10','023','الخبوزية','El Khabouzia','El Khabouzia'),
    ('10','024','الحاكمية','El-Hakimia','El-Hakimia'),
    ('10','025','المقراني','El-Mokrani','El-Mokrani'),
    ('10','026','قرومة','Guerrouma','Guerrouma'),
    ('10','027','الحجرة الزرقاء','Hadjera Zerga','Hadjera Zerga'),
    ('10','028','حيزر','Haizer','Haizer'),
    ('10','029','حنيف','Hanif','Hanif'),
    ('10','030','قادرية','Kadiria','Kadiria'),
    ('10','031','الأخضرية','Lakhdaria','Lakhdaria'),
    ('10','032','أمشدالة','M Chedallah','M Chedallah'),
    ('10','033','معلة','Maala','Maala'),
    ('10','034','المعمورة','Maamora','Maamora'),
    ('10','035','مزدور','Mezdour','Mezdour'),
    ('10','036','وادي البردي','Oued El Berdi','Oued El Berdi'),
    ('10','037','أولاد راشد','Ouled Rached','Ouled Rached'),
    ('10','038','روراوة','Raouraoua','Raouraoua'),
    ('10','039','ريدان','Ridane','Ridane'),
    ('10','040','سحاريج','Saharidj','Saharidj'),
    ('10','041','سوق الخميس','Souk El Khemis','Souk El Khemis'),
    ('10','042','سور الغزلان','Sour El Ghozlane','Sour El Ghozlane'),
    ('10','043','تاغزوت','Taghzout','Taghzout'),
    ('10','044','تاقديت','Taguedite','Taguedite'),
    ('10','045','زبربر','Z''barbar (El Isseri )','Z''barbar (El Isseri )'),
    ('11','001','ابلسة','Abelsa','Abelsa'),
    ('11','002','عين امقل','Ain Amguel','Ain Amguel'),
    ('11','003','أدلس','Idles','Idles'),
    ('11','004','تمنراست','Tamanrasset','Tamanrasset'),
    ('11','005','تاظروك','Tazrouk','Tazrouk'),
    ('12','001','عين الزرقاء','Ain Zerga','Ain Zerga'),
    ('12','002','بجن','Bedjene','Bedjene'),
    ('12','003','بكارية','Bekkaria','Bekkaria'),
    ('12','004','بئر الذهب','Bir Dheheb','Bir Dheheb'),
    ('12','005','بئر مقدم','Bir Mokkadem','Bir Mokkadem'),
    ('12','006','بئر العاتر','Bir-El-Ater','Bir-El-Ater'),
    ('12','007','بوخضرة','Boukhadra','Boukhadra'),
    ('12','008','بولحاف الدير','Boulhaf Dyr','Boulhaf Dyr'),
    ('12','009','الشريعة','Cheria','Cheria'),
    ('12','010','الكويف','El Kouif','El Kouif'),
    ('12','011','الماء الابيض','El Malabiod','El Malabiod'),
    ('12','012','المريج','El Meridj','El Meridj'),
    ('12','013','المزرعة','El Mezeraa','El Mezeraa'),
    ('12','014','العقلة','El Ogla','El Ogla'),
    ('12','015','العقلة المالحة','El Ogla El Malha','El Ogla El Malha'),
    ('12','016','العوينات','El-Aouinet','El-Aouinet'),
    ('12','017','الحويجبات','El-Houidjbet','El-Houidjbet'),
    ('12','018','فركان','Ferkane','Ferkane'),
    ('12','019','قريقر','Guorriguer','Guorriguer'),
    ('12','020','الحمامات','Hammamet','Hammamet'),
    ('12','021','مرسط','Morsott','Morsott'),
    ('12','022','نقرين','Negrine','Negrine'),
    ('12','023','الونزة','Ouenza','Ouenza'),
    ('12','024','أم علي','Oum Ali','Oum Ali'),
    ('12','025','صفصاف الوسرى','Saf Saf El Ouesra','Saf Saf El Ouesra'),
    ('12','026','سطح قنطيس','Stah Guentis','Stah Guentis'),
    ('12','027','تبسة','Tebessa','Tebessa'),
    ('12','028','ثليجان','Telidjen','Telidjen'),
    ('13','001','عين فتاح','Ain Fetah','Ain Fetah'),
    ('13','002','عين فزة','Ain Fezza','Ain Fezza'),
    ('13','003','عين غرابة','Ain Ghoraba','Ain Ghoraba'),
    ('13','004','عين الكبيرة','Ain Kebira','Ain Kebira'),
    ('13','005','عين النحالة','Ain Nehala','Ain Nehala'),
    ('13','006','عين تالوت','Ain Tellout','Ain Tellout'),
    ('13','007','عين يوسف','Ain Youcef','Ain Youcef'),
    ('13','008','عمير','Amieur','Amieur'),
    ('13','009','العزايل','Azail','Azail'),
    ('13','010','باب العسة','Bab El Assa','Bab El Assa'),
    ('13','011','بني بهدل','Beni Bahdel','Beni Bahdel'),
    ('13','012','بني بوسعيد','Beni Boussaid','Beni Boussaid'),
    ('13','013','بني خلاد','Beni Khellad','Beni Khellad'),
    ('13','014','بني مستر','Beni Mester','Beni Mester'),
    ('13','015','بني وارسوس','Beni Ouarsous','Beni Ouarsous'),
    ('13','016','بني صميل','Beni Smiel','Beni Smiel'),
    ('13','017','بني سنوس','Beni Snous','Beni Snous'),
    ('13','018','بن سكران','Bensekrane','Bensekrane'),
    ('13','019','بوحلو','Bouhlou','Bouhlou'),
    ('13','020','البويهي','Bouihi','Bouihi'),
    ('13','021','شتوان','Chetouane','Chetouane'),
    ('13','022','دار يغمراسن','Dar Yaghmoracen','Dar Yaghmoracen'),
    ('13','023','جبالة','Djebala','Djebala'),
    ('13','024','العريشة','El Aricha','El Aricha'),
    ('13','025','الفحول','El Fehoul','El Fehoul'),
    ('13','026','القور','El Gor','El Gor'),
    ('13','027','فلاوسن','Fellaoucene','Fellaoucene'),
    ('13','028','الغزوات','Ghazaouet','Ghazaouet'),
    ('13','029','حمام بوغرارة','Hammam Boughrara','Hammam Boughrara'),
    ('13','030','الحناية','Hennaya','Hennaya'),
    ('13','031','هنين','Honnaine','Honnaine'),
    ('13','032','مسيردة الفواقة','MSirda Fouaga','MSirda Fouaga'),
    ('13','033','مغنية','Maghnia','Maghnia'),
    ('13','034','منصورة','Mansourah','Mansourah'),
    ('13','035','مرسى بن مهيدي','Marsa Ben M''Hidi','Marsa Ben M''Hidi'),
    ('13','036','ندرومة','Nedroma','Nedroma'),
    ('13','037','وادي الخضر','Oued Lakhdar','Oued Lakhdar'),
    ('13','038','أولاد ميمون','Ouled Mimoun','Ouled Mimoun'),
    ('13','039','أولاد رياح','Ouled Riyah','Ouled Riyah'),
    ('13','040','الرمشي','Remchi','Remchi'),
    ('13','041','صبرة','Sabra','Sabra'),
    ('13','042','سبعة شيوخ','Sebbaa Chioukh','Sebbaa Chioukh'),
    ('13','043','سبدو','Sebdou','Sebdou'),
    ('13','044','سيدي العبدلي','Sidi Abdelli','Sidi Abdelli'),
    ('13','045','سيدي الجيلالي','Sidi Djillali','Sidi Djillali'),
    ('13','046','سيدي مجاهد','Sidi Medjahed','Sidi Medjahed'),
    ('13','047','السواحلية','Souahlia','Souahlia'),
    ('13','048','السواني','Souani','Souani'),
    ('13','049','سوق الثلاثاء','Souk Tleta','Souk Tleta'),
    ('13','050','تيرني بني هديل','Terny Beni Hediel','Terny Beni Hediel'),
    ('13','051','تيانت','Tianet','Tianet'),
    ('13','052','تلمسان','Tlemcen','Tlemcen'),
    ('13','053','زناتة','Zenata','Zenata'),
    ('14','001','عين بوشقيف','Ain Bouchekif','Ain Bouchekif'),
    ('14','002','عين الذهب','Ain Deheb','Ain Deheb'),
    ('14','003','عين دزاريت','Ain Dzarit','Ain Dzarit'),
    ('14','004','عين الحديد','Ain El Hadid','Ain El Hadid'),
    ('14','005','عين كرمس','Ain Kermes','Ain Kermes'),
    ('14','006','بوقرة','Bougara','Bougara'),
    ('14','007','شحيمة','Chehaima','Chehaima'),
    ('14','008','دحموني','Dahmouni','Dahmouni'),
    ('14','009','جبيلات الرصفاء','Djebilet Rosfa','Djebilet Rosfa'),
    ('14','010','جيلالي بن عمار','Djillali Ben Amar','Djillali Ben Amar'),
    ('14','011','الفايجة','Faidja','Faidja'),
    ('14','012','فرندة','Frenda','Frenda'),
    ('14','013','قرطوفة','Guertoufa','Guertoufa'),
    ('14','014','حمادية','Hamadia','Hamadia'),
    ('14','015','قصر الشلالة','Ksar Chellala','Ksar Chellala'),
    ('14','016','مادنة','Madna','Madna'),
    ('14','017','مهدية','Mahdia','Mahdia'),
    ('14','018','مشرع الصفا','Mechraa Safa','Mechraa Safa'),
    ('14','019','مدريسة','Medrissa','Medrissa'),
    ('14','020','مدروسة','Medroussa','Medroussa'),
    ('14','021','مغيلة','Meghila','Meghila'),
    ('14','022','ملاكو','Mellakou','Mellakou'),
    ('14','023','الناظورة','Nadorah','Nadorah'),
    ('14','024','النعيمة','Naima','Naima'),
    ('14','025','وادي ليلي','Oued Lilli','Oued Lilli'),
    ('14','026','الرحوية','Rahouia','Rahouia'),
    ('14','027','الرشايقة','Rechaiga','Rechaiga'),
    ('14','028','السبعين','Sebaine','Sebaine'),
    ('14','029','السبت','Sebt','Sebt'),
    ('14','030','سرغين','Serghine','Serghine'),
    ('14','031','سي عبد الغني','Si Abdelghani','Si Abdelghani'),
    ('14','032','سيدي عبد الرحمن','Sidi Abderrahmane','Sidi Abderrahmane'),
    ('14','033','سيدي علي ملال','Sidi Ali Mellal','Sidi Ali Mellal'),
    ('14','034','سيدي بختي','Sidi Bakhti','Sidi Bakhti'),
    ('14','035','سيدي حسني','Sidi Hosni','Sidi Hosni'),
    ('14','036','السوقر','Sougueur','Sougueur'),
    ('14','037','تاقدمت','Tagdempt','Tagdempt'),
    ('14','038','تخمرت','Takhemaret','Takhemaret'),
    ('14','039','تيارت','Tiaret','Tiaret'),
    ('14','040','تيدة','Tidda','Tidda'),
    ('14','041','توسنينة','Tousnina','Tousnina'),
    ('14','042','زمالة  الأمير عبد القادر','Zmalet El Emir Abdelkade','Zmalet El Emir Abdelkade'),
    ('15','001','أبي يوسف','Abi-Youcef','Abi-Youcef'),
    ('15','002','أغريب','Aghribs','Aghribs'),
    ('15','003','أقني قغران','Agouni-Gueghrane','Agouni-Gueghrane'),
    ('15','004','عين الحمام','Ain-El-Hammam','Ain-El-Hammam'),
    ('15','005','عين الزاوية','Ain-Zaouia','Ain-Zaouia'),
    ('15','006','أيت عقـواشة','Ait Aggouacha','Ait Aggouacha'),
    ('15','007','أيت بــوادو','Ait Bouaddou','Ait Bouaddou'),
    ('15','008','أيت بومهدي','Ait Boumahdi','Ait Boumahdi'),
    ('15','009','أيت خليلي','Ait Khellili','Ait Khellili'),
    ('15','010','أيت يحي موسى','Ait Yahia Moussa','Ait Yahia Moussa'),
    ('15','011','أيت عيسى ميمون','Ait-Aissa-Mimoun','Ait-Aissa-Mimoun'),
    ('15','012','أيت شافع','Ait-Chafaa','Ait-Chafaa'),
    ('15','013','أيت محمود','Ait-Mahmoud','Ait-Mahmoud'),
    ('15','014','أيت  أومالو','Ait-Oumalou','Ait-Oumalou'),
    ('15','015','أيت تودرت','Ait-Toudert','Ait-Toudert'),
    ('15','016','أيت يحيى','Ait-Yahia','Ait-Yahia'),
    ('15','017','اقبيل','Akbil','Akbil'),
    ('15','018','أقرو','Akerrou','Akerrou'),
    ('15','019','أسي يوسف','Assi-Youcef','Assi-Youcef'),
    ('15','020','عزازقة','Azazga','Azazga'),
    ('15','021','أزفون','Azeffoun','Azeffoun'),
    ('15','022','بنــــي زمنزار','Beni Zmenzer','Beni Zmenzer'),
    ('15','023','بني عيسي','Beni-Aissi','Beni-Aissi'),
    ('15','024','بني دوالة','Beni-Douala','Beni-Douala'),
    ('15','025','بني يني','Beni-Yenni','Beni-Yenni'),
    ('15','026','بني زيكــي','Beni-Zikki','Beni-Zikki'),
    ('15','027','بوغني','Boghni','Boghni'),
    ('15','028','بوجيمة','Boudjima','Boudjima'),
    ('15','029','بونوح','Bounouh','Bounouh'),
    ('15','030','بوزقــن','Bouzeguene','Bouzeguene'),
    ('15','031','ذراع بن خدة','Draa-Ben-Khedda','Draa-Ben-Khedda'),
    ('15','032','ذراع الميزان','Draa-El-Mizan','Draa-El-Mizan'),
    ('15','033','فريحة','Freha','Freha'),
    ('15','034','فريقات','Frikat','Frikat'),
    ('15','035','إبودرارن','Iboudrarene','Iboudrarene'),
    ('15','036','إيجــار','Idjeur','Idjeur'),
    ('15','037','إفــرحــونان','Iferhounene','Iferhounene'),
    ('15','038','إيفيغاء','Ifigha','Ifigha'),
    ('15','039','إفليـــسن','Iflissen','Iflissen'),
    ('15','040','إيلـيــلتـن','Illilten','Illilten'),
    ('15','041','إيلولة أومـــالو','Illoula Oumalou','Illoula Oumalou'),
    ('15','042','إمســوحال','Imsouhal','Imsouhal'),
    ('15','043','إيرجـــن','Irdjen','Irdjen'),
    ('15','044','الأربعــاء ناث إيراثن','Larbaa Nath Irathen','Larbaa Nath Irathen'),
    ('15','045','مكيرة','M''Kira','M''Kira'),
    ('15','046','معـــاتقة','Maatkas','Maatkas'),
    ('15','047','ماكودة','Makouda','Makouda'),
    ('15','048','مشطراس','Mechtras','Mechtras'),
    ('15','049','مقــلع','Mekla','Mekla'),
    ('15','050','ميزرانـــة','Mizrana','Mizrana'),
    ('15','051','واسيف','Ouacif','Ouacif'),
    ('15','052','واضية','Ouadhias','Ouadhias'),
    ('15','053','واقنون','Ouaguenoun','Ouaguenoun'),
    ('15','054','سيدي نعمان','Sidi Namane','Sidi Namane'),
    ('15','055','صوامـــع','Souama','Souama'),
    ('15','056','سوق الإثنين','Souk-El-Tenine','Souk-El-Tenine'),
    ('15','057','تادمايت','Tadmait','Tadmait'),
    ('15','058','تيقـزيرت','Tigzirt','Tigzirt'),
    ('15','059','تيمـيزار','Timizart','Timizart'),
    ('15','060','تيرمتين','Tirmitine','Tirmitine'),
    ('15','061','تيزي نثلاثة','Tizi N''Tleta','Tizi N''Tleta'),
    ('15','062','تيزي غنيف','Tizi-Gheniff','Tizi-Gheniff'),
    ('15','063','تيزي وزو','Tizi-Ouzou','Tizi-Ouzou'),
    ('15','064','تيزي راشد','Tizi-Rached','Tizi-Rached'),
    ('15','065','إعــكورن','Yakourene','Yakourene'),
    ('15','066','يطــافن','Yatafene','Yatafene'),
    ('15','067','زكري','Zekri','Zekri'),
    ('16','001','عين بنيان','Ain Benian','Ain Benian'),
    ('16','002','عين طاية','Ain Taya','Ain Taya'),
    ('16','003','الجزائر الوسطى','Alger Centre','Alger Centre'),
    ('16','004','باب الوادي','Bab El Oued','Bab El Oued'),
    ('16','005','باب الزوار','Bab Ezzouar','Bab Ezzouar'),
    ('16','006','بابا حسن','Baba Hassen','Baba Hassen'),
    ('16','007','باش جراح','Bachedjerah','Bachedjerah'),
    ('16','008','براقي','Baraki','Baraki'),
    ('16','009','ابن عكنون','Ben Aknoun','Ben Aknoun'),
    ('16','010','بني مسوس','Beni Messous','Beni Messous'),
    ('16','011','بئر مراد رايس','Bir Mourad Rais','Bir Mourad Rais'),
    ('16','012','بئر توتة','Bir Touta','Bir Touta'),
    ('16','013','بئر خادم','Birkhadem','Birkhadem'),
    ('16','014','بولوغين بن زيري','Bologhine Ibnou Ziri','Bologhine Ibnou Ziri'),
    ('16','015','برج البحري','Bordj El Bahri','Bordj El Bahri'),
    ('16','016','برج الكيفان','Bordj El Kiffan','Bordj El Kiffan'),
    ('16','017','بوروبة','Bourouba','Bourouba'),
    ('16','018','بوزريعة','Bouzareah','Bouzareah'),
    ('16','019','القصبة','Casbah','Casbah'),
    ('16','020','الشراقة','Cheraga','Cheraga'),
    ('16','021','الدار البيضاء','Dar El Beida','Dar El Beida'),
    ('16','022','دالي ابراهيم','Dely Ibrahim','Dely Ibrahim'),
    ('16','023','جسر قسنطينة','Djasr Kasentina','Djasr Kasentina'),
    ('16','024','الدويرة','Douira','Douira'),
    ('16','025','الدرارية','Draria','Draria'),
    ('16','026','العاشور','El Achour','El Achour'),
    ('16','027','الابيار','El Biar','El Biar'),
    ('16','028','الحراش','El Harrach','El Harrach'),
    ('16','029','المدنية','El Madania','El Madania'),
    ('16','030','المغارية','El Magharia','El Magharia'),
    ('16','031','المرسى','El Marsa','El Marsa'),
    ('16','032','المرادية','El Mouradia','El Mouradia'),
    ('16','033','الحمامات','Hammamet','Hammamet'),
    ('16','034','هراوة','Herraoua','Herraoua'),
    ('16','035','حسين داي','Hussein Dey','Hussein Dey'),
    ('16','036','حيدرة','Hydra','Hydra'),
    ('16','037','الخرايسية','Khraissia','Khraissia'),
    ('16','038','القبة','Kouba','Kouba'),
    ('16','039','الكاليتوس','Les Eucalyptus','Les Eucalyptus'),
    ('16','040','المعالمة','Maalma','Maalma'),
    ('16','041','محمد بلوزداد','Mohamed Belouzdad','Mohamed Belouzdad'),
    ('16','042','المحمدية','Mohammadia','Mohammadia'),
    ('16','043','وادي قريش','Oued Koriche','Oued Koriche'),
    ('16','044','وادي السمار','Oued Smar','Oued Smar'),
    ('16','045','اولاد شبل','Ouled Chebel','Ouled Chebel'),
    ('16','046','اولاد فايت','Ouled Fayet','Ouled Fayet'),
    ('16','047','الرحمانية','Rahmania','Rahmania'),
    ('16','048','الرايس حميدو','Rais Hamidou','Rais Hamidou'),
    ('16','049','رغاية','Reghaia','Reghaia'),
    ('16','050','الرويبة','Rouiba','Rouiba'),
    ('16','051','السحاولة','Sehaoula','Sehaoula'),
    ('16','052','سيدي امحمد','Sidi M''Hamed','Sidi M''Hamed'),
    ('16','053','سيدي موسى','Sidi Moussa','Sidi Moussa'),
    ('16','054','سويدانية','Souidania','Souidania'),
    ('16','055','سطاوالي','Staoueli','Staoueli'),
    ('16','056','تسالة المرجة','Tessala El Merdja','Tessala El Merdja'),
    ('16','057','زرالدة','Zeralda','Zeralda'),
    ('17','001','عين الشهداء','Ain Chouhada','Ain Chouhada'),
    ('17','002','عين الإبل','Ain El Ibel','Ain El Ibel'),
    ('17','003','عين فقه','Ain Fekka','Ain Fekka'),
    ('17','004','عين معبد','Ain Maabed','Ain Maabed'),
    ('17','005','عين وسارة','Ain Oussera','Ain Oussera'),
    ('17','006','عمورة','Amourah','Amourah'),
    ('17','007','بنهار','Benhar','Benhar'),
    ('17','008','بن يعقوب','Benyagoub','Benyagoub'),
    ('17','009','بيرين','Birine','Birine'),
    ('17','010','بويرة الأحداب','Bouira Lahdab','Bouira Lahdab'),
    ('17','011','الشارف','Charef','Charef'),
    ('17','012','دار الشيوخ','Dar Chioukh','Dar Chioukh'),
    ('17','013','دلدول','Deldoul','Deldoul'),
    ('17','014','الجلفة','Djelfa','Djelfa'),
    ('17','015','دويس','Douis','Douis'),
    ('17','016','القديد','El Guedid','El Guedid'),
    ('17','017','الادريسية','El Idrissia','El Idrissia'),
    ('17','018','الخميس','El Khemis','El Khemis'),
    ('17','019','فيض البطمة','Faidh El Botma','Faidh El Botma'),
    ('17','020','قرنيني','Guernini','Guernini'),
    ('17','021','قطارة','Guettara','Guettara'),
    ('17','022','حد الصحاري','Had Sahary','Had Sahary'),
    ('17','023','حاسي بحبح','Hassi Bahbah','Hassi Bahbah'),
    ('17','024','حاسي العش','Hassi El Euch','Hassi El Euch'),
    ('17','025','حاسي فدول','Hassi Fedoul','Hassi Fedoul'),
    ('17','026','مليليحة','M''Liliha','M''Liliha'),
    ('17','027','مسعد','Messaad','Messaad'),
    ('17','028','مجبارة','Moudjebara','Moudjebara'),
    ('17','029','أم العظام','Oum Laadham','Oum Laadham'),
    ('17','030','سد الرحال','Sed Rahal','Sed Rahal'),
    ('17','031','سلمانة','Selmana','Selmana'),
    ('17','032','سيدي بايزيد','Sidi Baizid','Sidi Baizid'),
    ('17','033','سيدي لعجال','Sidi Laadjel','Sidi Laadjel'),
    ('17','034','تعظميت','Taadmit','Taadmit'),
    ('17','035','زعفران','Zaafrane','Zaafrane'),
    ('17','036','زكار','Zaccar','Zaccar'),
    ('18','001','برج الطهر','Bordj T''har','Bordj T''har'),
    ('18','002','بودريعة بني  ياجيس','Boudria Beniyadjis','Boudria Beniyadjis'),
    ('18','003','بوراوي بلهادف','Bouraoui Belhadef','Bouraoui Belhadef'),
    ('18','004','بوسيف أولاد عسكر','Boussif Ouled Askeur','Boussif Ouled Askeur'),
    ('18','005','الشحنة','Chahna','Chahna'),
    ('18','006','الشقفة','Chekfa','Chekfa'),
    ('18','007','الجمعة بني حبيبي','Djemaa Beni Habibi','Djemaa Beni Habibi'),
    ('18','008','جيملة','Djimla','Djimla'),
    ('18','009','العنصر','El Ancer','El Ancer'),
    ('18','010','العوانة','El Aouana','El Aouana'),
    ('18','011','القنار نشفي','El Kennar Nouchfi','El Kennar Nouchfi'),
    ('18','012','الميلية','El Milia','El Milia'),
    ('18','013','الامير عبد القادر','Emir Abdelkader','Emir Abdelkader'),
    ('18','014','أراقن سويسي','Erraguene Souissi','Erraguene Souissi'),
    ('18','015','غبالة','Ghebala','Ghebala'),
    ('18','016','جيجل','Jijel','Jijel'),
    ('18','017','قاوس','Kaous','Kaous'),
    ('18','018','خيري واد عجول','Khiri Oued Adjoul','Khiri Oued Adjoul'),
    ('18','019','وجانة','Oudjana','Oudjana'),
    ('18','020','أولاد رابح','Ouled Rabah','Ouled Rabah'),
    ('18','021','أولاد يحيى خدروش','Ouled Yahia Khadrouch','Ouled Yahia Khadrouch'),
    ('18','022','سلمى بن زيادة','Selma Benziada','Selma Benziada'),
    ('18','023','السطارة','Settara','Settara'),
    ('18','024','سيدي عبد العزيز','Sidi Abdelaziz','Sidi Abdelaziz'),
    ('18','025','سيدي معروف','Sidi Marouf','Sidi Marouf'),
    ('18','026','الطاهير','Taher','Taher'),
    ('18','027','تاكسنة','Texenna','Texenna'),
    ('18','028','زيامة منصورية','Ziama Mansouriah','Ziama Mansouriah'),
    ('19','001','عين عباسة','Ain Abessa','Ain Abessa'),
    ('19','002','عين أرنات','Ain Arnat','Ain Arnat'),
    ('19','003','عين أزال','Ain Azel','Ain Azel'),
    ('19','004','عين الكبيرة','Ain El Kebira','Ain El Kebira'),
    ('19','005','عين الحجر','Ain Lahdjar','Ain Lahdjar'),
    ('19','006','عين ولمان','Ain Oulmene','Ain Oulmene'),
    ('19','007','عين لقراج','Ain-Legradj','Ain-Legradj'),
    ('19','008','عين الروى','Ain-Roua','Ain-Roua'),
    ('19','009','عين السبت','Ain-Sebt','Ain-Sebt'),
    ('19','010','أيت نوال مزادة','Ait Naoual Mezada','Ait Naoual Mezada'),
    ('19','011','ايت تيزي','Ait-Tizi','Ait-Tizi'),
    ('19','012','عموشة','Amoucha','Amoucha'),
    ('19','013','بابور','Babor','Babor'),
    ('19','014','بازر سكرة','Bazer-Sakra','Bazer-Sakra'),
    ('19','015','بيضاء برج','Beidha Bordj','Beidha Bordj'),
    ('19','016','بلاعة','Bellaa','Bellaa'),
    ('19','017','بني شبانة','Beni Chebana','Beni Chebana'),
    ('19','018','بني فودة','Beni Fouda','Beni Fouda'),
    ('19','019','بني ورتيلان','Beni Ourtilane','Beni Ourtilane'),
    ('19','020','بني وسين','Beni Oussine','Beni Oussine'),
    ('19','021','بني عزيز','Beni-Aziz','Beni-Aziz'),
    ('19','022','بني موحلي','Beni-Mouhli','Beni-Mouhli'),
    ('19','023','بئر حدادة','Bir Haddada','Bir Haddada'),
    ('19','024','بئر العرش','Bir-El-Arch','Bir-El-Arch'),
    ('19','025','بوعنداس','Bouandas','Bouandas'),
    ('19','026','بوقاعة','Bougaa','Bougaa'),
    ('19','027','بوسلام','Bousselam','Bousselam'),
    ('19','028','بوطالب','Boutaleb','Boutaleb'),
    ('19','029','الدهامشة','Dehamcha','Dehamcha'),
    ('19','030','جميلة','Djemila','Djemila'),
    ('19','031','ذراع قبيلة','Draa-Kebila','Draa-Kebila'),
    ('19','032','العلمة','El Eulma','El Eulma'),
    ('19','033','أوريسيا','El Ouricia','El Ouricia'),
    ('19','034','الولجة','El-Ouldja','El-Ouldja'),
    ('19','035','قلال','Guellal','Guellal'),
    ('19','036','قلتة زرقاء','Guelta Zerka','Guelta Zerka'),
    ('19','037','قنزات','Guenzet','Guenzet'),
    ('19','038','قجال','Guidjel','Guidjel'),
    ('19','039','حمام السخنة','Hamam Soukhna','Hamam Soukhna'),
    ('19','040','الحامة','Hamma','Hamma'),
    ('19','041','حمام قرقور','Hammam Guergour','Hammam Guergour'),
    ('19','042','حربيل','Harbil','Harbil'),
    ('19','043','قصر الابطال','Kasr El Abtal','Kasr El Abtal'),
    ('19','044','معاوية','Maaouia','Maaouia'),
    ('19','045','ماوكلان','Maouaklane','Maouaklane'),
    ('19','046','مزلوق','Mezloug','Mezloug'),
    ('19','047','واد البارد','Oued El Bared','Oued El Bared'),
    ('19','048','أولاد عدوان','Ouled Addouane','Ouled Addouane'),
    ('19','049','أولاد صابر','Ouled Sabor','Ouled Sabor'),
    ('19','050','أولاد سي أحمد','Ouled Si Ahmed','Ouled Si Ahmed'),
    ('19','051','أولاد تبان','Ouled Tebben','Ouled Tebben'),
    ('19','052','الرصفة','Rosfa','Rosfa'),
    ('19','053','صالح باي','Salah Bey','Salah Bey'),
    ('19','054','سرج الغول','Serdj-El-Ghoul','Serdj-El-Ghoul'),
    ('19','055','سطيف','Setif','Setif'),
    ('19','056','تاشودة','Tachouda','Tachouda'),
    ('19','057','تالة إيفاسن','Tala-Ifacene','Tala-Ifacene'),
    ('19','058','الطاية','Taya','Taya'),
    ('19','059','التلة','Tella','Tella'),
    ('19','060','تيزي نبشار','Tizi N''Bechar','Tizi N''Bechar'),
    ('20','001','عين السخونة','Ain Sekhouna','Ain Sekhouna'),
    ('20','002','عين الحجر','Aïn El Hadjar','Aïn El Hadjar'),
    ('20','003','عين السلطان','Aïn Soltane','Aïn Soltane'),
    ('20','004','دوي ثابت','Doui Thabet','Doui Thabet'),
    ('20','005','الحساسنة','El Hassasna','El Hassasna'),
    ('20','006','هونت','Hounet','Hounet'),
    ('20','007','المعمورة','Maamora','Maamora'),
    ('20','008','مولاي العربي','Moulay Larbi','Moulay Larbi'),
    ('20','009','أولاد إبراهيم','Ouled Brahim','Ouled Brahim'),
    ('20','010','أولاد خالد','Ouled Khaled','Ouled Khaled'),
    ('20','011','سعيدة','Saida','Saida'),
    ('20','012','سيدي احمد','Sidi Ahmed','Sidi Ahmed'),
    ('20','013','سيدي عمر','Sidi Amar','Sidi Amar'),
    ('20','014','سيدي بوبكر','Sidi Boubekeur','Sidi Boubekeur'),
    ('20','015','تيرسين','Tircine','Tircine'),
    ('20','016','يوب','Youb','Youb'),
    ('21','001','عين بوزيان','Ain Bouziane','Ain Bouziane'),
    ('21','002','عين شرشار','Ain Charchar','Ain Charchar'),
    ('21','003','عين قشرة','Ain Kechra','Ain Kechra'),
    ('21','004','عين زويت','Ain Zouit','Ain Zouit'),
    ('21','005','عزابة','Azzaba','Azzaba'),
    ('21','006','بكوش لخضر','Bekkouche Lakhdar','Bekkouche Lakhdar'),
    ('21','007','بن عزوز','Ben Azzouz','Ben Azzouz'),
    ('21','008','بني بشير','Beni Bechir','Beni Bechir'),
    ('21','009','بني ولبان','Beni Oulbane','Beni Oulbane'),
    ('21','010','بني زيد','Beni Zid','Beni Zid'),
    ('21','011','بين الويدان','Bin El Ouiden','Bin El Ouiden'),
    ('21','012','بوشطاطة','Bouchetata','Bouchetata'),
    ('21','013','الشرايع','Cheraia','Cheraia'),
    ('21','014','القل','Collo','Collo'),
    ('21','015','جندل سعدي محمد','Djendel Saadi Mohamed','Djendel Saadi Mohamed'),
    ('21','016','الحروش','El Arrouch','El Arrouch'),
    ('21','017','الغدير','El Ghedir','El Ghedir'),
    ('21','018','الحدائق','El Hadaiek','El Hadaiek'),
    ('21','019','المرسى','El Marsa','El Marsa'),
    ('21','020','مجاز الدشيش','Emjez Edchich','Emjez Edchich'),
    ('21','021','السبت','Es Sebt','Es Sebt'),
    ('21','022','فلفلة','Filfila','Filfila'),
    ('21','023','حمادي كرومة','Hammadi Krouma','Hammadi Krouma'),
    ('21','024','قنواع','Kanoua','Kanoua'),
    ('21','025','الكركرة','Kerkara','Kerkara'),
    ('21','026','خناق مايو','Khenag Maoune','Khenag Maoune'),
    ('21','027','وادي الزهور','Oued Zhour','Oued Zhour'),
    ('21','028','الولجة بولبلوط','Ouldja Boulbalout','Ouldja Boulbalout'),
    ('21','029','أولاد عطية','Ouled Attia','Ouled Attia'),
    ('21','030','أولاد حبابة','Ouled Habbaba','Ouled Habbaba'),
    ('21','031','أم الطوب','Oum Toub','Oum Toub'),
    ('21','032','رمضان جمال','Ramdane Djamel','Ramdane Djamel'),
    ('21','033','صالح بو الشعور','Salah Bouchaour','Salah Bouchaour'),
    ('21','034','سيدي مزغيش','Sidi Mezghiche','Sidi Mezghiche'),
    ('21','035','سكيكدة','Skikda','Skikda'),
    ('21','036','تمالوس','Tamalous','Tamalous'),
    ('21','037','زردازة','Zerdezas','Zerdezas'),
    ('21','038','الزيتونة','Zitouna','Zitouna'),
    ('22','001','عين البرد','Ain El Berd','Ain El Berd'),
    ('22','002','عين قادة','Ain Kada','Ain Kada'),
    ('22','003','عين الثريد','Ain Thrid','Ain Thrid'),
    ('22','004','عين تندمين','Ain Tindamine','Ain Tindamine'),
    ('22','005','عين أدن','Ain- Adden','Ain- Adden'),
    ('22','006','العمارنة','Amarnas','Amarnas'),
    ('22','007','بضرابين المقراني','Bedrabine El Mokrani','Bedrabine El Mokrani'),
    ('22','008','بلعربي','Belarbi','Belarbi'),
    ('22','009','بن باديس','Ben Badis','Ben Badis'),
    ('22','010','بن عشيبة شلية','Benachiba Chelia','Benachiba Chelia'),
    ('22','011','بئر الحمام','Bir El Hammam','Bir El Hammam'),
    ('22','012','بوجبهة البرج','Boudjebaa El Bordj','Boudjebaa El Bordj'),
    ('22','013','بوخنفيس','Boukhanefis','Boukhanefis'),
    ('22','014','شيطوان البلايلة','Chetouane Belaila','Chetouane Belaila'),
    ('22','015','الضاية','Dhaya','Dhaya'),
    ('22','016','الحصيبة','El Hacaiba','El Hacaiba'),
    ('22','017','حاسي دحو','Hassi Dahou','Hassi Dahou'),
    ('22','018','حاسي زهانة','Hassi Zahana','Hassi Zahana'),
    ('22','019','لمطار','Lamtar','Lamtar'),
    ('22','020','مسيد','M''Cid','M''Cid'),
    ('22','021','مكدرة','Makedra','Makedra'),
    ('22','022','مرحوم','Marhoum','Marhoum'),
    ('22','023','مرين','Merine','Merine'),
    ('22','024','مزاورو','Mezaourou','Mezaourou'),
    ('22','025','مصطفى بن ابراهيم','Mostefa Ben Brahim','Mostefa Ben Brahim'),
    ('22','026','مولاي سليسن','Moulay Slissen','Moulay Slissen'),
    ('22','027','وادي السبع','Oued Sebaa','Oued Sebaa'),
    ('22','028','وادي سفيون','Oued Sefioun','Oued Sefioun'),
    ('22','029','وادي تاوريرة','Oued Taourira','Oued Taourira'),
    ('22','030','راس الماء','Ras El Ma','Ras El Ma'),
    ('22','031','رجم دموش','Redjem Demouche','Redjem Demouche'),
    ('22','032','السهالة الثورة','Sehala Thaoura','Sehala Thaoura'),
    ('22','033','سفيزف','Sfisef','Sfisef'),
    ('22','034','سيدي علي بن يوب','Sidi Ali Benyoub','Sidi Ali Benyoub'),
    ('22','035','سيدي علي بوسيدي','Sidi Ali Boussidi','Sidi Ali Boussidi'),
    ('22','036','سيدي بلعباس','Sidi Bel-Abbes','Sidi Bel-Abbes'),
    ('22','037','سيدي ابراهيم','Sidi Brahim','Sidi Brahim'),
    ('22','038','سيدي شعيب','Sidi Chaib','Sidi Chaib'),
    ('22','039','سيدي دحو الزاير','Sidi Dahou Zairs','Sidi Dahou Zairs'),
    ('22','040','سيدي حمادوش','Sidi Hamadouche','Sidi Hamadouche'),
    ('22','041','سيدي خالد','Sidi Khaled','Sidi Khaled'),
    ('22','042','سيدي لحسن','Sidi Lahcene','Sidi Lahcene'),
    ('22','043','سيدي يعقوب','Sidi Yacoub','Sidi Yacoub'),
    ('22','044','طابية','Tabia','Tabia'),
    ('22','045','تاودموت','Taoudmout','Taoudmout'),
    ('22','046','تفسور','Tefessour','Tefessour'),
    ('22','047','تغاليمت','Teghalimet','Teghalimet'),
    ('22','048','تلاغ','Telagh','Telagh'),
    ('22','049','تنيرة','Tenira','Tenira'),
    ('22','050','تسالة','Tessala','Tessala'),
    ('22','051','تلموني','Tilmouni','Tilmouni'),
    ('22','052','زروالة','Zerouala','Zerouala'),
    ('23','001','عين الباردة','Ain El Berda','Ain El Berda'),
    ('23','002','عنابة','Annaba','Annaba'),
    ('23','003','برحال','Berrahal','Berrahal'),
    ('23','004','شطايبي','Chetaibi','Chetaibi'),
    ('23','005','الشرفة','Cheurfa','Cheurfa'),
    ('23','006','البوني','El Bouni','El Bouni'),
    ('23','007','العلمة','El Eulma','El Eulma'),
    ('23','008','الحجار','El Hadjar','El Hadjar'),
    ('23','009','واد العنب','Oued El Aneb','Oued El Aneb'),
    ('23','010','سرايدي','Seraidi','Seraidi'),
    ('23','011','سيدي عمار','Sidi Amar','Sidi Amar'),
    ('23','012','التريعات','Treat','Treat'),
    ('24','001','عين بن بيضاء','Ain Ben Beida','Ain Ben Beida'),
    ('24','002','عين العربي','Ain Larbi','Ain Larbi'),
    ('24','003','عين مخلوف','Ain Makhlouf','Ain Makhlouf'),
    ('24','004','عين رقادة','Ain Regada','Ain Regada'),
    ('24','005','عين صندل','Ain Sandel','Ain Sandel'),
    ('24','006','بلخير','Belkheir','Belkheir'),
    ('24','007','بن جراح','Bendjarah','Bendjarah'),
    ('24','008','بني مزلين','Beni Mezline','Beni Mezline'),
    ('24','009','برج صباط','Bordj Sabath','Bordj Sabath'),
    ('24','010','بوحشانة','Bou Hachana','Bou Hachana'),
    ('24','011','بوحمدان','Bou Hamdane','Bou Hamdane'),
    ('24','012','بوعاتي محمود','Bouati Mahmoud','Bouati Mahmoud'),
    ('24','013','بوشقوف','Bouchegouf','Bouchegouf'),
    ('24','014','بومهرة أحمد','Boumahra Ahmed','Boumahra Ahmed'),
    ('24','015','الدهوارة','Dahouara','Dahouara'),
    ('24','016','جبالة الخميسي','Djeballah Khemissi','Djeballah Khemissi'),
    ('24','017','الفجوج','El Fedjoudj','El Fedjoudj'),
    ('24','018','قلعة بوصبع','Guelaat Bou Sbaa','Guelaat Bou Sbaa'),
    ('24','019','قالمة','Guelma','Guelma'),
    ('24','020','حمام دباغ','Hammam Debagh','Hammam Debagh'),
    ('24','021','حمام النبايل','Hammam N''Bail','Hammam N''Bail'),
    ('24','022','هيليوبوليس','Heliopolis','Heliopolis'),
    ('24','023','هواري بومدين','Houari Boumedienne','Houari Boumedienne'),
    ('24','024','لخزارة','Khezaras','Khezaras'),
    ('24','025','مجاز عمار','Medjez Amar','Medjez Amar'),
    ('24','026','مجاز الصفاء','Medjez Sfa','Medjez Sfa'),
    ('24','027','نشماية','Nechmaya','Nechmaya'),
    ('24','028','وادي الشحم','Oued Cheham','Oued Cheham'),
    ('24','029','وادي فراغة','Oued Ferragha','Oued Ferragha'),
    ('24','030','وادي الزناتي','Oued Zenati','Oued Zenati'),
    ('24','031','رأس العقبة','Ras El Agba','Ras El Agba'),
    ('24','032','الركنية','Roknia','Roknia'),
    ('24','033','سلاوة عنونة','Sellaoua Announa','Sellaoua Announa'),
    ('24','034','تاملوكة','Tamlouka','Tamlouka'),
    ('25','001','عين عبيد','Ain Abid','Ain Abid'),
    ('25','002','عين السمارة','Ain Smara','Ain Smara'),
    ('25','003','أبن باديس الهرية','Ben Badis','Ben Badis'),
    ('25','004','بني حميدان','Beni Hamidane','Beni Hamidane'),
    ('25','005','قسنطينة','Constantine','Constantine'),
    ('25','006','ديدوش مراد','Didouche Mourad','Didouche Mourad'),
    ('25','007','الخروب','El Khroub','El Khroub'),
    ('25','008','حامة بوزيان','Hamma Bouziane','Hamma Bouziane'),
    ('25','009','ابن زياد','Ibn Ziad','Ibn Ziad'),
    ('25','010','بوجريو مسعود','Messaoud Boudjeriou','Messaoud Boudjeriou'),
    ('25','011','أولاد رحمون','Ouled Rahmoun','Ouled Rahmoun'),
    ('25','012','زيغود يوسف','Zighoud Youcef','Zighoud Youcef'),
    ('26','001','عين بوسيف','Ain Boucif','Ain Boucif'),
    ('26','002','عين اقصير','Ain Ouksir','Ain Ouksir'),
    ('26','003','العيساوية','Aissaouia','Aissaouia'),
    ('26','004','عزيز','Aziz','Aziz'),
    ('26','005','بعطة','Baata','Baata'),
    ('26','006','بن شكاو','Ben Chicao','Ben Chicao'),
    ('26','007','بني سليمان','Beni Slimane','Beni Slimane'),
    ('26','008','البرواقية','Berrouaghia','Berrouaghia'),
    ('26','009','بئر بن عابد','Bir Ben Laabed','Bir Ben Laabed'),
    ('26','010','بوغار','Boghar','Boghar'),
    ('26','011','بوعيش','Bouaiche','Bouaiche'),
    ('26','012','بوعيشون','Bouaichoune','Bouaichoune'),
    ('26','013','بوشراحيل','Bouchrahil','Bouchrahil'),
    ('26','014','بوغزول','Boughzoul','Boughzoul'),
    ('26','015','بوسكن','Bouskene','Bouskene'),
    ('26','016','الشهبونية','Chabounia','Chabounia'),
    ('26','017','شلالة العذاورة','Chelalet El Adhaoura','Chelalet El Adhaoura'),
    ('26','018','شنيقل','Cheniguel','Cheniguel'),
    ('26','019','دراق','Derrag','Derrag'),
    ('26','020','جواب','Djouab','Djouab'),
    ('26','021','ذراع السمار','Draa Esmar','Draa Esmar'),
    ('26','022','العزيزية','El Azizia','El Azizia'),
    ('26','023','القلب الكبير','El Guelbelkebir','El Guelbelkebir'),
    ('26','024','الحمدانية','El Hamdania','El Hamdania'),
    ('26','025','الحوضان','El Haoudane','El Haoudane'),
    ('26','026','العمارية','El Omaria','El Omaria'),
    ('26','027','العوينات','El Ouinet','El Ouinet'),
    ('26','028','حناشة','Hannacha','Hannacha'),
    ('26','029','الكاف الاخضر','Kef Lakhdar','Kef Lakhdar'),
    ('26','030','خمس جوامع','Khams Djouamaa','Khams Djouamaa'),
    ('26','031','قصر البخاري','Ksar El Boukhari','Ksar El Boukhari'),
    ('26','032','مفاتحة','M''fatha','M''fatha'),
    ('26','033','مغراوة','Maghraoua','Maghraoua'),
    ('26','034','المدية','Medea','Medea'),
    ('26','035','مجبر','Medjebar','Medjebar'),
    ('26','036','مزغنة','Mezerana','Mezerana'),
    ('26','037','ميهوب','Mihoub','Mihoub'),
    ('26','038','عوامري','Ouamri','Ouamri'),
    ('26','039','وادي حربيل','Oued Harbil','Oued Harbil'),
    ('26','040','أولاد عنتر','Ouled Antar','Ouled Antar'),
    ('26','041','أولاد بوعشرة','Ouled Bouachra','Ouled Bouachra'),
    ('26','042','أولاد إبراهيم','Ouled Brahim','Ouled Brahim'),
    ('26','043','أولاد دايد','Ouled Deid','Ouled Deid'),
    ('26','044','أولاد امعرف','Ouled Emaaraf','Ouled Emaaraf'),
    ('26','045','أولاد هلال','Ouled Hellal','Ouled Hellal'),
    ('26','046','أم الجليل','Oum El Djellil','Oum El Djellil'),
    ('26','047','وزرة','Ouzera','Ouzera'),
    ('26','048','الربعية','Rebaia','Rebaia'),
    ('26','049','السانق','Saneg','Saneg'),
    ('26','050','سدراية','Sedraya','Sedraya'),
    ('26','051','سغوان','Seghouane','Seghouane'),
    ('26','052','سي المحجوب','Si Mahdjoub','Si Mahdjoub'),
    ('26','053','سيدي دامد','Sidi Demed','Sidi Demed'),
    ('26','054','سيدي نعمان','Sidi Naamane','Sidi Naamane'),
    ('26','055','سيدي الربيع','Sidi Rabie','Sidi Rabie'),
    ('26','056','سيدي زهار','Sidi Zahar','Sidi Zahar'),
    ('26','057','سيدي زيان','Sidi Ziane','Sidi Ziane'),
    ('26','058','السواقي','Souagui','Souagui'),
    ('26','059','تابلاط','Tablat','Tablat'),
    ('26','060','تفراوت','Tafraout','Tafraout'),
    ('26','061','تمسقيدة','Tamesguida','Tamesguida'),
    ('26','062','تيزي مهدي','Tizi Mahdi','Tizi Mahdi'),
    ('26','063','ثلاث دوائر','Tletat Ed Douair','Tletat Ed Douair'),
    ('26','064','الزبيرية','Zoubiria','Zoubiria'),
    ('27','001','عشعاشة','Achaacha','Achaacha'),
    ('27','002','عين بودينار','Ain-Boudinar','Ain-Boudinar'),
    ('27','003','عين نويسي','Ain-Nouissy','Ain-Nouissy'),
    ('27','004','عين سيدي الشريف','Ain-Sidi Cherif','Ain-Sidi Cherif'),
    ('27','005','عين تادلس','Ain-Tedles','Ain-Tedles'),
    ('27','006','بن عبد المالك رمضان','Benabdelmalek Ramdane','Benabdelmalek Ramdane'),
    ('27','007','بوقيراط','Bouguirat','Bouguirat'),
    ('27','008','فرناقة','Fornaka','Fornaka'),
    ('27','009','حجاج','Hadjadj','Hadjadj'),
    ('27','010','حاسي ماماش','Hassi Mameche','Hassi Mameche'),
    ('27','011','الحسيان (بني ياحي','Hassiane','Hassiane'),
    ('27','012','خضرة','Khadra','Khadra'),
    ('27','013','خير الدين','Kheir-Eddine','Kheir-Eddine'),
    ('27','014','منصورة','Mansourah','Mansourah'),
    ('27','015','مزغران','Mazagran','Mazagran'),
    ('27','016','ماسرة','Mesra','Mesra'),
    ('27','017','مستغانم','Mostaganem','Mostaganem'),
    ('27','018','نكمارية','Nekmaria','Nekmaria'),
    ('27','019','وادي الخير','Oued El Kheir','Oued El Kheir'),
    ('27','020','أولاد بوغالم','Ouled Boughalem','Ouled Boughalem'),
    ('27','021','أولاد مع الله','Ouled-Maalah','Ouled-Maalah'),
    ('27','022','صفصاف','Safsaf','Safsaf'),
    ('27','023','صيادة','Sayada','Sayada'),
    ('27','024','سيدي علي','Sidi Ali','Sidi Ali'),
    ('27','025','سيدي بلعطار','Sidi Belaattar','Sidi Belaattar'),
    ('27','026','سيدي لخضر','Sidi-Lakhdar','Sidi-Lakhdar'),
    ('27','027','سيرات','Sirat','Sirat'),
    ('27','028','السوافلية','Souaflia','Souaflia'),
    ('27','029','سور','Sour','Sour'),
    ('27','030','ستيدية','Stidia','Stidia'),
    ('27','031','تزقايت','Tazgait','Tazgait'),
    ('27','032','الطواهرية','Touahria','Touahria'),
    ('28','001','عين الحجل','Ain El Hadjel','Ain El Hadjel'),
    ('28','002','عين الملح','Ain El Melh','Ain El Melh'),
    ('28','003','عين فارس','Ain Fares','Ain Fares'),
    ('28','004','عين الخضراء','Ain Khadra','Ain Khadra'),
    ('28','005','عين الريش','Ain Rich','Ain Rich'),
    ('28','006','بلعايبة','Belaiba','Belaiba'),
    ('28','007','بن سرور','Ben Srour','Ben Srour'),
    ('28','008','بني يلمان','Beni Ilmane','Beni Ilmane'),
    ('28','009','بن زوه','Benzouh','Benzouh'),
    ('28','010','برهوم','Berhoum','Berhoum'),
    ('28','011','بئر فضة','Bir Foda','Bir Foda'),
    ('28','012','بوسعادة','Bou Saada','Bou Saada'),
    ('28','013','بوطي السايح','Bouti Sayeh','Bouti Sayeh'),
    ('28','014','شلال','Chellal','Chellal'),
    ('28','015','دهاهنة','Dehahna','Dehahna'),
    ('28','016','جبل مساعد','Djebel Messaad','Djebel Messaad'),
    ('28','017','الهامل','El Hamel','El Hamel'),
    ('28','018','الحوامد','El Houamed','El Houamed'),
    ('28','019','حمام الضلعة','Hammam Dalaa','Hammam Dalaa'),
    ('28','020','خطوطي سد الجير','Khettouti Sed-El-Jir','Khettouti Sed-El-Jir'),
    ('28','021','خبانة','Khoubana','Khoubana'),
    ('28','022','مسيف','M''Cif','M''Cif'),
    ('28','023','المسيلة','M''Sila','M''Sila'),
    ('28','024','المطارفة','M''Tarfa','M''Tarfa'),
    ('28','025','المعاضيد','Maadid','Maadid'),
    ('28','026','معاريف','Maarif','Maarif'),
    ('28','027','مقرة','Magra','Magra'),
    ('28','028','امجدل','Medjedel','Medjedel'),
    ('28','029','مناعة','Menaa','Menaa'),
    ('28','030','محمد بوضياف','Mohamed Boudiaf','Mohamed Boudiaf'),
    ('28','031','ونوغة','Ouanougha','Ouanougha'),
    ('28','032','أولاد عدي لقبالة','Ouled Addi Guebala','Ouled Addi Guebala'),
    ('28','033','أولاد دراج','Ouled Derradj','Ouled Derradj'),
    ('28','034','أولاد ماضي','Ouled Madhi','Ouled Madhi'),
    ('28','035','أولاد منصور','Ouled Mansour','Ouled Mansour'),
    ('28','036','أولاد سيدي ابراهيم','Ouled Sidi Brahim','Ouled Sidi Brahim'),
    ('28','037','أولاد سليمان','Ouled Slimane','Ouled Slimane'),
    ('28','038','ولتام','Oulteme','Oulteme'),
    ('28','039','سيدي عيسى','Sidi Aissa','Sidi Aissa'),
    ('28','040','سيدي عامر','Sidi Ameur','Sidi Ameur'),
    ('28','041','سيدي هجرس','Sidi Hadjeres','Sidi Hadjeres'),
    ('28','042','سيدي امحمد','Sidi M''Hamed','Sidi M''Hamed'),
    ('28','043','سليم','Slim','Slim'),
    ('28','044','السوامع','Souamaa','Souamaa'),
    ('28','045','تامسة','Tamsa','Tamsa'),
    ('28','046','تارمونت','Tarmount','Tarmount'),
    ('28','047','زرزور','Zarzour','Zarzour'),
    ('29','001','عين فارس','Ain Fares','Ain Fares'),
    ('29','002','عين فكان','Ain Fekan','Ain Fekan'),
    ('29','003','عين فراح','Ain Ferah','Ain Ferah'),
    ('29','004','عين أفرص','Ain Frass','Ain Frass'),
    ('29','005','العلايمية','Alaimia','Alaimia'),
    ('29','006','عوف','Aouf','Aouf'),
    ('29','007','بنيان','Benian','Benian'),
    ('29','008','بوهني','Bou Henni','Bou Henni'),
    ('29','009','بوحنيفية','Bouhanifia','Bouhanifia'),
    ('29','010','الشرفاء','Chorfa','Chorfa'),
    ('29','011','البرج','El Bordj','El Bordj'),
    ('29','012','القعدة','El Gaada','El Gaada'),
    ('29','013','الغمري','El Ghomri','El Ghomri'),
    ('29','014','القطنة','El Gueitena','El Gueitena'),
    ('29','015','الحشم','El Hachem','El Hachem'),
    ('29','016','القرط','El Keurt','El Keurt'),
    ('29','017','المأمونية','El Mamounia','El Mamounia'),
    ('29','018','المنور','El Menaouer','El Menaouer'),
    ('29','019','فراقيق','Ferraguig','Ferraguig'),
    ('29','020','فروحة','Froha','Froha'),
    ('29','021','غروس','Gharrous','Gharrous'),
    ('29','022','غريس','Ghriss','Ghriss'),
    ('29','023','قرجوم','Guerdjoum','Guerdjoum'),
    ('29','024','حسين','Hacine','Hacine'),
    ('29','025','خلوية','Khalouia','Khalouia'),
    ('29','026','ماقضة','Makhda','Makhda'),
    ('29','027','ماوسة','Maoussa','Maoussa'),
    ('29','028','معسكر','Mascara','Mascara'),
    ('29','029','المطمور','Matemore','Matemore'),
    ('29','030','مقطع الدوز','Mocta-Douz','Mocta-Douz'),
    ('29','031','المحمدية','Mohammadia','Mohammadia'),
    ('29','032','نسمط','Nesmot','Nesmot'),
    ('29','033','عقاز','Oggaz','Oggaz'),
    ('29','034','وادي الأبطال','Oued El Abtal','Oued El Abtal'),
    ('29','035','وادي التاغية','Oued Taria','Oued Taria'),
    ('29','036','رأس عين عميروش','Ras El Ain Amirouche','Ras El Ain Amirouche'),
    ('29','037','سجرارة','Sedjerara','Sedjerara'),
    ('29','038','السهايلية','Sehailia','Sehailia'),
    ('29','039','سيدي عبد الجبار','Sidi Abdeldjebar','Sidi Abdeldjebar'),
    ('29','040','سيدي عبد المومن','Sidi Abdelmoumene','Sidi Abdelmoumene'),
    ('29','041','سيدي بوسعيد','Sidi Boussaid','Sidi Boussaid'),
    ('29','042','سيدي قادة','Sidi Kada','Sidi Kada'),
    ('29','043','سيق','Sig','Sig'),
    ('29','044','تيغنيف','Tighennif','Tighennif'),
    ('29','045','تيزي','Tizi','Tizi'),
    ('29','046','زهانة','Zahana','Zahana'),
    ('29','047','زلامطة','Zelamta','Zelamta'),
    ('30','001','عين البيضاء','Ain Beida','Ain Beida'),
    ('30','002','البرمة','El Borma','El Borma'),
    ('30','003','حاسي بن عبد الله','Hassi Ben Abdellah','Hassi Ben Abdellah'),
    ('30','004','حاسي مسعود','Hassi Messaoud','Hassi Messaoud'),
    ('30','005','انقوسة','N''Goussa','N''Goussa'),
    ('30','006','ورقلة','Ouargla','Ouargla'),
    ('30','007','الرويسات','Rouissat','Rouissat'),
    ('30','008','سيدي خويلد','Sidi Khouiled','Sidi Khouiled'),
    ('31','001','عين البية','Ain Biya','Ain Biya'),
    ('31','002','عين الكرمة','Ain Kerma','Ain Kerma'),
    ('31','003','عين الترك','Ain Turk','Ain Turk'),
    ('31','004','أرزيو','Arzew','Arzew'),
    ('31','005','بن فريحة','Ben Freha','Ben Freha'),
    ('31','006','بطيوة','Bethioua','Bethioua'),
    ('31','007','بئر الجير','Bir El Djir','Bir El Djir'),
    ('31','008','بوفاتيس','Boufatis','Boufatis'),
    ('31','009','بوسفر','Bousfer','Bousfer'),
    ('31','010','بوتليليس','Boutlelis','Boutlelis'),
    ('31','011','العنصر','El Ancor','El Ancor'),
    ('31','012','البراية','El Braya','El Braya'),
    ('31','013','الكرمة','El Kerma','El Kerma'),
    ('31','014','السانية','Es Senia','Es Senia'),
    ('31','015','قديل','Gdyel','Gdyel'),
    ('31','016','حاسي بن عقبة','Hassi Ben Okba','Hassi Ben Okba'),
    ('31','017','حاسي بونيف','Hassi Bounif','Hassi Bounif'),
    ('31','018','حاسي مفسوخ','Hassi Mefsoukh','Hassi Mefsoukh'),
    ('31','019','مرسى الحجاج','Marsat El Hadjadj','Marsat El Hadjadj'),
    ('31','020','المرسى الكبير','Mers El Kebir','Mers El Kebir'),
    ('31','021','مسرغين','Messerghin','Messerghin'),
    ('31','022','وهران','Oran','Oran'),
    ('31','023','وادي تليلات','Oued Tlelat','Oued Tlelat'),
    ('31','024','سيدي بن يبقى','Sidi Ben Yebka','Sidi Ben Yebka'),
    ('31','025','سيدي الشحمي','Sidi Chami','Sidi Chami'),
    ('31','026','طفراوي','Tafraoui','Tafraoui'),
    ('32','001','اربوات','Arbaouat','Arbaouat'),
    ('32','002','عين العراك','Aïn El Orak','Aïn El Orak'),
    ('32','003','بوعلام','Boualem','Boualem'),
    ('32','004','بوقطب','Bougtoub','Bougtoub'),
    ('32','005','بوسمغون','Boussemghoun','Boussemghoun'),
    ('32','006','بريزينة','Brezina','Brezina'),
    ('32','007','الشقيق','Cheguig','Cheguig'),
    ('32','008','شلالة','Chellala','Chellala'),
    ('32','009','البيض','El Bayadh','El Bayadh'),
    ('32','010','البنود','El Bnoud','El Bnoud'),
    ('32','011','الخيثر','El Kheiter','El Kheiter'),
    ('32','012','المحرة','El Mehara','El Mehara'),
    ('32','013','الغاسول','Ghassoul','Ghassoul'),
    ('32','014','الكاف الأحمر','Kef El Ahmar','Kef El Ahmar'),
    ('32','015','كراكدة','Krakda','Krakda'),
    ('32','016','الأبيض سيدي الشيخ','Labiodh Sidi Cheikh','Labiodh Sidi Cheikh'),
    ('32','017','رقاصة','Rogassa','Rogassa'),
    ('32','018','سيدي عامر','Sidi Ameur','Sidi Ameur'),
    ('32','019','سيدي سليمان','Sidi Slimane','Sidi Slimane'),
    ('32','020','سيدي طيفور','Sidi Tiffour','Sidi Tiffour'),
    ('32','021','ستيتن','Stitten','Stitten'),
    ('32','022','توسمولين','Tousmouline','Tousmouline'),
    ('33','001','برج عمر إدريس','Bordj Omar Driss','Bordj Omar Driss'),
    ('33','002','دبداب','Debdeb','Debdeb'),
    ('33','003','إيليزي','Illizi','Illizi'),
    ('33','004','إن أمناس','In Amenas','In Amenas'),
    ('34','001','عين تاغروت','Ain Taghrout','Ain Taghrout'),
    ('34','002','عين تسرة','Ain Tesra','Ain Tesra'),
    ('34','003','برج بوعريرج','B. B. Arreridj','B. B. Arreridj'),
    ('34','004','بليمور','Belimour','Belimour'),
    ('34','005','بن داود','Ben Daoud','Ben Daoud'),
    ('34','006','بئر قاصد علي','Bir Kasdali','Bir Kasdali'),
    ('34','007','برج الغدير','Bordj Ghedir','Bordj Ghedir'),
    ('34','008','برج زمورة','Bordj Zemmoura','Bordj Zemmoura'),
    ('34','009','القلة','Colla','Colla'),
    ('34','010','جعافرة','Djaafra','Djaafra'),
    ('34','011','الياشير','El Achir','El Achir'),
    ('34','012','العناصر','El Annasseur','El Annasseur'),
    ('34','013','العش','El Euch','El Euch'),
    ('34','014','المهير','El M''hir','El M''hir'),
    ('34','015','الماين','El Main','El Main'),
    ('34','016','الحمادية','Elhammadia','Elhammadia'),
    ('34','017','غيلاسة','Ghailasa','Ghailasa'),
    ('34','018','حرازة','Haraza','Haraza'),
    ('34','019','حسناوة','Hasnaoua','Hasnaoua'),
    ('34','020','خليل','Khelil','Khelil'),
    ('34','021','القصور','Ksour','Ksour'),
    ('34','022','المنصورة','Mansoura','Mansoura'),
    ('34','023','مجانة','Medjana','Medjana'),
    ('34','024','أولاد أبراهم','Ouled Brahem','Ouled Brahem'),
    ('34','025','أولاد دحمان','Ouled Dahmane','Ouled Dahmane'),
    ('34','026','أولاد سيدي ابراهيم','Ouled Sidi-Brahim','Ouled Sidi-Brahim'),
    ('34','027','الرابطة','Rabta','Rabta'),
    ('34','028','رأس الوادي','Ras El Oued','Ras El Oued'),
    ('34','029','سيدي أمبارك','Sidi-Embarek','Sidi-Embarek'),
    ('34','030','تقلعيت','Taglait','Taglait'),
    ('34','031','تسامرت','Tassamert','Tassamert'),
    ('34','032','تفرق','Tefreg','Tefreg'),
    ('34','033','ثنية النصر','Teniet En Nasr','Teniet En Nasr'),
    ('34','034','تيكستار','Tixter','Tixter'),
    ('35','001','أعفير','Afir','Afir'),
    ('35','002','عمال','Ammal','Ammal'),
    ('35','003','بغلية','Baghlia','Baghlia'),
    ('35','004','بن شود','Ben Choud','Ben Choud'),
    ('35','005','بني عمران','Beni Amrane','Beni Amrane'),
    ('35','006','برج منايل','Bordj Menaiel','Bordj Menaiel'),
    ('35','007','بودواو','Boudouaou','Boudouaou'),
    ('35','008','بودواو البحري','Boudouaou El Bahri','Boudouaou El Bahri'),
    ('35','009','بومرداس','Boumerdes','Boumerdes'),
    ('35','010','بوزقزة قدارة','Bouzegza Keddara','Bouzegza Keddara'),
    ('35','011','شعبة العامر','Chabet El Ameur','Chabet El Ameur'),
    ('35','012','قورصو','Corso','Corso'),
    ('35','013','دلس','Dellys','Dellys'),
    ('35','014','جنات','Djinet','Djinet'),
    ('35','015','الخروبة','El Kharrouba','El Kharrouba'),
    ('35','016','حمادي','Hammedi','Hammedi'),
    ('35','017','يسر','Isser','Isser'),
    ('35','018','خميس الخشنة','Khemis El Khechna','Khemis El Khechna'),
    ('35','019','الاربعطاش','Larbatache','Larbatache'),
    ('35','020','لقاطة','Leghata','Leghata'),
    ('35','021','الناصرية','Naciria','Naciria'),
    ('35','022','أولاد عيسى','Ouled Aissa','Ouled Aissa'),
    ('35','023','أولاد هداج','Ouled Hedadj','Ouled Hedadj'),
    ('35','024','أولاد موسى','Ouled Moussa','Ouled Moussa'),
    ('35','025','سي مصطفى','Si Mustapha','Si Mustapha'),
    ('35','026','سيدي داود','Sidi Daoud','Sidi Daoud'),
    ('35','027','سوق الحد','Souk El Had','Souk El Had'),
    ('35','028','تاورقة','Taourga','Taourga'),
    ('35','029','الثنية','Thenia','Thenia'),
    ('35','030','تيجلابين','Tidjelabine','Tidjelabine'),
    ('35','031','تيمزريت','Timezrit','Timezrit'),
    ('35','032','زموري','Zemmouri','Zemmouri'),
    ('36','001','عين العسل','Ain El Assel','Ain El Assel'),
    ('36','002','عين الكرمة','Ain Kerma','Ain Kerma'),
    ('36','003','عصفور','Asfour','Asfour'),
    ('36','004','بن مهيدي','Ben M Hidi','Ben M Hidi'),
    ('36','005','بريحان','Berrihane','Berrihane'),
    ('36','006','البسباس','Besbes','Besbes'),
    ('36','007','بوقوس','Bougous','Bougous'),
    ('36','008','بوحجار','Bouhadjar','Bouhadjar'),
    ('36','009','بوثلجة','Bouteldja','Bouteldja'),
    ('36','010','شبيطة مختار','Chebaita Mokhtar','Chebaita Mokhtar'),
    ('36','011','الشافية','Chefia','Chefia'),
    ('36','012','شحاني','Chihani','Chihani'),
    ('36','013','الذرعـان','Drean','Drean'),
    ('36','014','الشط','Echatt','Echatt'),
    ('36','015','العيون','El Aioun','El Aioun'),
    ('36','016','القالة','El Kala','El Kala'),
    ('36','017','الطارف','El Tarf','El Tarf'),
    ('36','018','حمام بني صالح','Hammam Beni Salah','Hammam Beni Salah'),
    ('36','019','بحيرة الطيور','Lac Des Oiseaux','Lac Des Oiseaux'),
    ('36','020','وادي الزيتون','Oued Zitoun','Oued Zitoun'),
    ('36','021','رمل السوق','Raml Souk','Raml Souk'),
    ('36','022','السوارخ','Souarekh','Souarekh'),
    ('36','023','زريزر','Zerizer','Zerizer'),
    ('36','024','الزيتونة','Zitouna','Zitouna'),
    ('37','001','أم العسل','Oum El Assel','Oum El Assel'),
    ('37','002','تندوف','Tindouf','Tindouf'),
    ('38','001','عماري','Ammari','Ammari'),
    ('38','002','بني شعيب','Beni Chaib','Beni Chaib'),
    ('38','003','بني لحسن','Beni Lahcene','Beni Lahcene'),
    ('38','004','برج بونعامة','Bordj Bounaama','Bordj Bounaama'),
    ('38','005','برج الأمير عبد القادر','Bordj El Emir Abdelkader','Bordj El Emir Abdelkader'),
    ('38','006','بوقائد','Boucaid','Boucaid'),
    ('38','007','خميستي','Khemisti','Khemisti'),
    ('38','008','الأربعاء','Larbaa','Larbaa'),
    ('38','009','لرجام','Lardjem','Lardjem'),
    ('38','010','العيون','Layoune','Layoune'),
    ('38','011','الأزهرية','Lazharia','Lazharia'),
    ('38','012','المعاصم','Maacem','Maacem'),
    ('38','013','الملعب','Melaab','Melaab'),
    ('38','014','أولاد بسام','Ouled Bessam','Ouled Bessam'),
    ('38','015','سيدي عابد','Sidi Abed','Sidi Abed'),
    ('38','016','سيدي بوتوشنت','Sidi Boutouchent','Sidi Boutouchent'),
    ('38','017','سيدي العنتري','Sidi Lantri','Sidi Lantri'),
    ('38','018','سيدي سليمان','Sidi Slimane','Sidi Slimane'),
    ('38','019','تملاحت','Tamellahet','Tamellahet'),
    ('38','020','ثنية الاحد','Theniet El Had','Theniet El Had'),
    ('38','021','تيسمسيلت','Tissemsilt','Tissemsilt'),
    ('38','022','اليوسفية','Youssoufia','Youssoufia'),
    ('39','001','البياضة','Bayadha','Bayadha'),
    ('39','002','بن  قشة','Ben Guecha','Ben Guecha'),
    ('39','003','الدبيلة','Debila','Debila'),
    ('39','004','دوار الماء','Douar El Maa','Douar El Maa'),
    ('39','005','العقلة','El Ogla','El Ogla'),
    ('39','006','الوادي','El-Oued','El-Oued'),
    ('39','007','قمار','Guemar','Guemar'),
    ('39','008','الحمراية','Hamraia','Hamraia'),
    ('39','009','حساني عبد الكريم','Hassani Abdelkrim','Hassani Abdelkrim'),
    ('39','010','حاسي خليفة','Hassi Khalifa','Hassi Khalifa'),
    ('39','011','كوينين','Kouinine','Kouinine'),
    ('39','012','المقرن','Magrane','Magrane'),
    ('39','013','اميه وانسة','Mih Ouansa','Mih Ouansa'),
    ('39','014','النخلة','Nakhla','Nakhla'),
    ('39','015','وادي العلندة','Oued El Alenda','Oued El Alenda'),
    ('39','016','ورماس','Ourmes','Ourmes'),
    ('39','017','الرقيبة','Reguiba','Reguiba'),
    ('39','018','الرباح','Robbah','Robbah'),
    ('39','019','سيدي عون','Sidi Aoun','Sidi Aoun'),
    ('39','020','تغزوت','Taghzout','Taghzout'),
    ('39','021','الطالب العربي','Taleb Larbi','Taleb Larbi'),
    ('39','022','الطريفاوي','Trifaoui','Trifaoui'),
    ('40','001','عين الطويلة','Ain Touila','Ain Touila'),
    ('40','002','بابار','Babar','Babar'),
    ('40','003','بغاي','Baghai','Baghai'),
    ('40','004','بوحمامة','Bouhmama','Bouhmama'),
    ('40','005','ششار','Chechar','Chechar'),
    ('40','006','شلية','Chelia','Chelia'),
    ('40','007','جلال','Djellal','Djellal'),
    ('40','008','الحامة','El Hamma','El Hamma'),
    ('40','009','المحمل','El Mahmal','El Mahmal'),
    ('40','010','الولجة','El Oueldja','El Oueldja'),
    ('40','011','انسيغة','Ensigha','Ensigha'),
    ('40','012','قايس','Kais','Kais'),
    ('40','013','خنشلة','Khenchela','Khenchela'),
    ('40','014','خيران','Khirane','Khirane'),
    ('40','015','مصارة','M''Sara','M''Sara'),
    ('40','016','متوسة','M''Toussa','M''Toussa'),
    ('40','017','أولاد رشاش','Ouled Rechache','Ouled Rechache'),
    ('40','018','الرميلة','Remila','Remila'),
    ('40','019','طامزة','Tamza','Tamza'),
    ('40','020','تاوزيانت','Taouzianat','Taouzianat'),
    ('40','021','يابوس','Yabous','Yabous'),
    ('41','001','عين سلطان','Ain Soltane','Ain Soltane'),
    ('41','002','عين الزانة','Ain Zana','Ain Zana'),
    ('41','003','بئر بوحوش','Bir Bouhouche','Bir Bouhouche'),
    ('41','004','الدريعة','Drea','Drea'),
    ('41','005','الحدادة','Haddada','Haddada'),
    ('41','006','الحنانشة','Hanencha','Hanencha'),
    ('41','007','الخضارة','Khedara','Khedara'),
    ('41','008','خميسة','Khemissa','Khemissa'),
    ('41','009','مداوروش','M''daourouche','M''daourouche'),
    ('41','010','المشروحة','Machroha','Machroha'),
    ('41','011','المراهنة','Merahna','Merahna'),
    ('41','012','وادي الكبريت','Oued Kebrit','Oued Kebrit'),
    ('41','013','ويلان','Ouillen','Ouillen'),
    ('41','014','أولاد إدريس','Ouled Driss','Ouled Driss'),
    ('41','015','أولاد مومن','Ouled Moumen','Ouled Moumen'),
    ('41','016','أم العظايم','Oum El Adhaim','Oum El Adhaim'),
    ('41','017','الراقوبة','Ragouba','Ragouba'),
    ('41','018','سافل الويدان','Safel El Ouiden','Safel El Ouiden'),
    ('41','019','سدراتة','Sedrata','Sedrata'),
    ('41','020','سيدي فرج','Sidi Fredj','Sidi Fredj'),
    ('41','021','سوق أهراس','Souk Ahras','Souk Ahras'),
    ('41','022','تاورة','Taoura','Taoura'),
    ('41','023','ترقالت','Terraguelt','Terraguelt'),
    ('41','024','تيفاش','Tiffech','Tiffech'),
    ('41','025','الزعرورية','Zaarouria','Zaarouria'),
    ('41','026','الزوابي','Zouabi','Zouabi'),
    ('42','001','أغبال','Aghbal','Aghbal'),
    ('42','002','أحمر العين','Ahmer El Ain','Ahmer El Ain'),
    ('42','003','عين تاقورايت','Ain Tagourait','Ain Tagourait'),
    ('42','004','الحطاطبة','Attatba','Attatba'),
    ('42','005','بني ميلك','Beni Mileuk','Beni Mileuk'),
    ('42','006','بوهارون','Bou Haroun','Bou Haroun'),
    ('42','007','بواسماعيل','Bou Ismail','Bou Ismail'),
    ('42','008','بورقيقة','Bourkika','Bourkika'),
    ('42','009','الشعيبة','Chaiba','Chaiba'),
    ('42','010','شرشال','Cherchell','Cherchell'),
    ('42','011','الداموس','Damous','Damous'),
    ('42','012','دواودة','Douaouda','Douaouda'),
    ('42','013','فوكة','Fouka','Fouka'),
    ('42','014','قوراية','Gouraya','Gouraya'),
    ('42','015','حجوط','Hadjout','Hadjout'),
    ('42','016','حجرة النص','Hadjret Ennous','Hadjret Ennous'),
    ('42','017','خميستي','Khemisti','Khemisti'),
    ('42','018','القليعة','Kolea','Kolea'),
    ('42','019','الأرهاط','Larhat','Larhat'),
    ('42','020','مناصر','Menaceur','Menaceur'),
    ('42','021','مراد','Merad','Merad'),
    ('42','022','مسلمون','Messelmoun','Messelmoun'),
    ('42','023','الناظور','Nador','Nador'),
    ('42','024','سيدي غيلاس','Sidi Ghiles','Sidi Ghiles'),
    ('42','025','سيدي راشد','Sidi Rached','Sidi Rached'),
    ('42','026','سيدي سميان','Sidi Semiane','Sidi Semiane'),
    ('42','027','سيدي عامر','Sidi-Amar','Sidi-Amar'),
    ('42','028','تيبازة','Tipaza','Tipaza'),
    ('43','001','أحمد راشدي','Ahmed Rachedi','Ahmed Rachedi'),
    ('43','002','عين البيضاء أحريش','Ain Beida Harriche','Ain Beida Harriche'),
    ('43','003','عين الملوك','Ain Mellouk','Ain Mellouk'),
    ('43','004','عين التين','Ain Tine','Ain Tine'),
    ('43','005','اعميرة اراس','Amira Arres','Amira Arres'),
    ('43','006','بن يحي عبد الرحمن','Benyahia Abderrahmane','Benyahia Abderrahmane'),
    ('43','007','بوحاتم','Bouhatem','Bouhatem'),
    ('43','008','شلغوم العيد','Chelghoum Laid','Chelghoum Laid'),
    ('43','009','الشيقارة','Chigara','Chigara'),
    ('43','010','دراحي بوصلاح','Derrahi Bousselah','Derrahi Bousselah'),
    ('43','011','العياضي برباس','El Ayadi Barbes','El Ayadi Barbes'),
    ('43','012','مشيرة','El Mechira','El Mechira'),
    ('43','013','فرجيوة','Ferdjioua','Ferdjioua'),
    ('43','014','القرارم قوقة','Grarem Gouga','Grarem Gouga'),
    ('43','015','حمالة','Hamala','Hamala'),
    ('43','016','ميلة','Mila','Mila'),
    ('43','017','مينار زارزة','Minar Zarza','Minar Zarza'),
    ('43','018','وادي العثمانية','Oued Athmenia','Oued Athmenia'),
    ('43','019','وادي النجاء','Oued Endja','Oued Endja'),
    ('43','020','وادي سقان','Oued Seguen','Oued Seguen'),
    ('43','021','أولاد اخلوف','Ouled Khalouf','Ouled Khalouf'),
    ('43','022','الرواشد','Rouached','Rouached'),
    ('43','023','سيدي خليفة','Sidi Khelifa','Sidi Khelifa'),
    ('43','024','سيدي مروان','Sidi Merouane','Sidi Merouane'),
    ('43','025','تاجنانت','Tadjenanet','Tadjenanet'),
    ('43','026','تسدان حدادة','Tassadane Haddada','Tassadane Haddada'),
    ('43','027','تسالة لمطاعي','Tassala Lematai','Tassala Lematai'),
    ('43','028','التلاغمة','Teleghma','Teleghma'),
    ('43','029','ترعي باينان','Terrai Bainen','Terrai Bainen'),
    ('43','030','تيبرقنت','Tiberguent','Tiberguent'),
    ('43','031','يحي بني قشة','Yahia Beniguecha','Yahia Beniguecha'),
    ('43','032','زغاية','Zeghaia','Zeghaia'),
    ('44','001','عين البنيان','Ain-Benian','Ain-Benian'),
    ('44','002','عين بويحيى','Ain-Bouyahia','Ain-Bouyahia'),
    ('44','003','عين الدفلى','Ain-Defla','Ain-Defla'),
    ('44','004','عين الاشياخ','Ain-Lechiakh','Ain-Lechiakh'),
    ('44','005','عين السلطان','Ain-Soltane','Ain-Soltane'),
    ('44','006','عين التركي','Ain-Torki','Ain-Torki'),
    ('44','007','عريب','Arib','Arib'),
    ('44','008','بطحية','Bathia','Bathia'),
    ('44','009','بلعاص','Belaas','Belaas'),
    ('44','010','بن علال','Ben Allal','Ben Allal'),
    ('44','011','بئر ولد خليفة','Bir-Ould-Khelifa','Bir-Ould-Khelifa'),
    ('44','012','بربوش','Birbouche','Birbouche'),
    ('44','013','برج الأمير خالد','Bordj-Emir-Khaled','Bordj-Emir-Khaled'),
    ('44','014','بومدفع','Boumedfaa','Boumedfaa'),
    ('44','015','بوراشد','Bourached','Bourached'),
    ('44','016','جليدة','Djelida','Djelida'),
    ('44','017','جمعة أولاد الشيخ','Djemaa Ouled Cheikh','Djemaa Ouled Cheikh'),
    ('44','018','جندل','Djendel','Djendel'),
    ('44','019','العبادية','El-Abadia','El-Abadia'),
    ('44','020','العامرة','El-Amra','El-Amra'),
    ('44','021','العطاف','El-Attaf','El-Attaf'),
    ('44','022','الماين','El-Maine','El-Maine'),
    ('44','023','حمام ريغة','Hammam-Righa','Hammam-Righa'),
    ('44','024','الحسانية','Hassania','Hassania'),
    ('44','025','الحسينية','Hoceinia','Hoceinia'),
    ('44','026','خميس مليانة','Khemis-Miliana','Khemis-Miliana'),
    ('44','027','المخاطرية','Mekhatria','Mekhatria'),
    ('44','028','مليانة','Miliana','Miliana'),
    ('44','029','وادي الشرفاء','Oued Chorfa','Oued Chorfa'),
    ('44','030','واد الجمعة','Oued Djemaa','Oued Djemaa'),
    ('44','031','الروينة','Rouina','Rouina'),
    ('44','032','سيدي الأخضر','Sidi-Lakhdar','Sidi-Lakhdar'),
    ('44','033','تاشتة زقاغة','Tacheta Zegagha','Tacheta Zegagha'),
    ('44','034','طارق بن زياد','Tarik-Ibn-Ziad','Tarik-Ibn-Ziad'),
    ('44','035','تبركانين','Tiberkanine','Tiberkanine'),
    ('44','036','زدين','Zeddine','Zeddine'),
    ('45','001','عين بن خليل','Ain Ben Khelil','Ain Ben Khelil'),
    ('45','002','عين الصفراء','Ain Sefra','Ain Sefra'),
    ('45','003','عسلة','Asla','Asla'),
    ('45','004','جنين بورزق','Djenienne Bourezg','Djenienne Bourezg'),
    ('45','005','البيوض','El Biodh','El Biodh'),
    ('45','006','القصدير','Kasdir','Kasdir'),
    ('45','007','مكمن بن عمار','Makmen Ben Amar','Makmen Ben Amar'),
    ('45','008','المشرية','Mecheria','Mecheria'),
    ('45','009','مغرار','Moghrar','Moghrar'),
    ('45','010','النعامة','Naama','Naama'),
    ('45','011','سفيسيفة','Sfissifa','Sfissifa'),
    ('45','012','تيوت','Tiout','Tiout'),
    ('46','001','أغلال','Aghlal','Aghlal'),
    ('46','002','عين الأربعاء','Ain El Arbaa','Ain El Arbaa'),
    ('46','003','عين الكيحل','Ain Kihal','Ain Kihal'),
    ('46','004','عين تموشنت','Ain Temouchent','Ain Temouchent'),
    ('46','005','عين الطلبة','Ain Tolba','Ain Tolba'),
    ('46','006','عقب الليل','Aoubellil','Aoubellil'),
    ('46','007','بني صاف','Beni Saf','Beni Saf'),
    ('46','008','بوزجار','Bouzedjar','Bouzedjar'),
    ('46','009','شعبة اللحم','Chaabat El Ham','Chaabat El Ham'),
    ('46','010','شنتوف','Chentouf','Chentouf'),
    ('46','011','العامرية','El Amria','El Amria'),
    ('46','012','المالح','El Maleh','El Maleh'),
    ('46','013','المساعيد','El Messaid','El Messaid'),
    ('46','014','الأمير عبد القادر','Emir Abdelkader','Emir Abdelkader'),
    ('46','015','حمام بوحجر','Hammam Bou Hadjar','Hammam Bou Hadjar'),
    ('46','016','الحساسنة','Hassasna','Hassasna'),
    ('46','017','حاسي الغلة','Hassi El Ghella','Hassi El Ghella'),
    ('46','018','وادي برقش','Oued Berkeche','Oued Berkeche'),
    ('46','019','وادي الصباح','Oued Sebbah','Oued Sebbah'),
    ('46','020','أولاد بوجمعة','Ouled Boudjemaa','Ouled Boudjemaa'),
    ('46','021','أولاد الكيحل','Ouled Kihal','Ouled Kihal'),
    ('46','022','ولهاصة الغرابة','Oulhaca El Gheraba','Oulhaca El Gheraba'),
    ('46','023','سيدي بن عدة','Sidi Ben Adda','Sidi Ben Adda'),
    ('46','024','سيدي بومدين','Sidi Boumediene','Sidi Boumediene'),
    ('46','025','سيدي ورياش','Sidi Ouriache','Sidi Ouriache'),
    ('46','026','سيدي صافي','Sidi Safi','Sidi Safi'),
    ('46','027','تامزورة','Tamzoura','Tamzoura'),
    ('46','028','تارقة','Terga','Terga'),
    ('47','001','بريان','Berriane','Berriane'),
    ('47','002','بونورة','Bounoura','Bounoura'),
    ('47','003','ضاية بن ضحوة','Dhayet Bendhahoua','Dhayet Bendhahoua'),
    ('47','004','العطف','El Atteuf','El Atteuf'),
    ('47','005','القرارة','El Guerrara','El Guerrara'),
    ('47','006','غرداية','Ghardaia','Ghardaia'),
    ('47','007','المنصورة','Mansoura','Mansoura'),
    ('47','008','متليلي','Metlili','Metlili'),
    ('47','009','سبسب','Sebseb','Sebseb'),
    ('47','010','زلفانة','Zelfana','Zelfana'),
    ('48','001','عين الرحمة','Ain Rahma','Ain Rahma'),
    ('48','002','عين طارق','Ain-Tarek','Ain-Tarek'),
    ('48','003','عمي موسى','Ammi Moussa','Ammi Moussa'),
    ('48','004','بلعسل بوزقزة','Belaassel Bouzagza','Belaassel Bouzagza'),
    ('48','005','بن داود','Bendaoud','Bendaoud'),
    ('48','006','بني درقن','Beni Dergoun','Beni Dergoun'),
    ('48','007','بني زنطيس','Beni Zentis','Beni Zentis'),
    ('48','008','دار بن عبد الله','Dar Ben Abdelah','Dar Ben Abdelah'),
    ('48','009','جديوية','Djidiouia','Djidiouia'),
    ('48','010','الحمادنة','El H''madna','El H''madna'),
    ('48','011','الحاسي','El Hassi','El Hassi'),
    ('48','012','الولجة','El Ouldja','El Ouldja'),
    ('48','013','القطار','El-Guettar','El-Guettar'),
    ('48','014','المطمر','El-Matmar','El-Matmar'),
    ('48','015','حد الشكالة','Had Echkalla','Had Echkalla'),
    ('48','016','حمري','Hamri','Hamri'),
    ('48','017','القلعة','Kalaa','Kalaa'),
    ('48','018','لحلاف','Lahlef','Lahlef'),
    ('48','019','مازونة','Mazouna','Mazouna'),
    ('48','020','مديونة','Mediouna','Mediouna'),
    ('48','021','منداس','Mendes','Mendes'),
    ('48','022','مرجة سيدي عابد','Merdja Sidi Abed','Merdja Sidi Abed'),
    ('48','023','واريزان','Ouarizane','Ouarizane'),
    ('48','024','وادي الجمعة','Oued El Djemaa','Oued El Djemaa'),
    ('48','025','وادي السلام','Oued Essalem','Oued Essalem'),
    ('48','026','وادي رهيو','Oued-Rhiou','Oued-Rhiou'),
    ('48','027','أولاد يعيش','Ouled Aiche','Ouled Aiche'),
    ('48','028','أولاد سيدي الميهوب','Ouled Sidi Mihoub','Ouled Sidi Mihoub'),
    ('48','029','الرمكة','Ramka','Ramka'),
    ('48','030','غليزان','Relizane','Relizane'),
    ('48','031','سيدي  خطاب','Sidi Khettab','Sidi Khettab'),
    ('48','032','سيدي لزرق','Sidi Lazreg','Sidi Lazreg'),
    ('48','033','سيدي امحمد بن عودة','Sidi M''Hamed Benaouda','Sidi M''Hamed Benaouda'),
    ('48','034','سيدي أمحمد بن علي','Sidi M''hamed Benali','Sidi M''hamed Benali'),
    ('48','035','سيدي سعادة','Sidi Saada','Sidi Saada'),
    ('48','036','سوق الحد','Souk El Had','Souk El Had'),
    ('48','037','يلل','Yellel','Yellel'),
    ('48','038','زمورة','Zemmoura','Zemmoura'),
    ('49','001','أوقروت','Aougrout','Aougrout'),
    ('49','002','شروين','Charouine','Charouine'),
    ('49','003','دلدول','Deldoul','Deldoul'),
    ('49','004','قصر قدور','Ksar Kaddour','Ksar Kaddour'),
    ('49','005','المطارفة','Metarfa','Metarfa'),
    ('49','006','أولاد عيسى','Ouled Aissa','Ouled Aissa'),
    ('49','007','أولاد السعيد','Ouled Said','Ouled Said'),
    ('49','008','طالمين','Talmine','Talmine'),
    ('49','009','تيميمون','Timimoun','Timimoun'),
    ('49','010','تنركوك','Tinerkouk','Tinerkouk'),
    ('50','001','برج باجي مختار','Bordj Badji Mokhtar','Bordj Badji Mokhtar'),
    ('50','002','تيمياوين','Timiaouine','Timiaouine'),
    ('51','001','بسباس','Besbes','Besbes'),
    ('51','002','الشعيبة','Chaiba','Chaiba'),
    ('51','003','الدوسن','Doucen','Doucen'),
    ('51','004','أولاد جلال','Ouled Djellal','Ouled Djellal'),
    ('51','005','رأس الميعاد','Ras El Miad','Ras El Miad'),
    ('51','006','سيدي  خالد','Sidi Khaled','Sidi Khaled'),
    ('52','001','بن يخلف','Beni Ikhlef','Beni Ikhlef'),
    ('52','002','بني عباس','Béni Abbès','Béni Abbès'),
    ('52','003','الواتة','El Ouata','El Ouata'),
    ('52','004','إقلي','Igli','Igli'),
    ('52','005','كرزاز','Kerzaz','Kerzaz'),
    ('52','006','القصابي','Ksabi','Ksabi'),
    ('52','007','أولاد خضير','Ouled-Khodeir','Ouled-Khodeir'),
    ('52','008','تبلبالة','Tabelbala','Tabelbala'),
    ('52','009','تامترت','Tamtert','Tamtert'),
    ('52','010','تيمودي','Timoudi','Timoudi'),
    ('53','001','عين صالح','Ain Salah','Ain Salah'),
    ('53','002','فقارة الزوى','Foggaret Ezzoua','Foggaret Ezzoua'),
    ('53','003','إينغر','Inghar','Inghar'),
    ('54','001','عين قزام','Ain Guezzam','Ain Guezzam'),
    ('54','002','تين زواتين','Tin Zouatine','Tin Zouatine'),
    ('55','001','بن ناصر','Benaceur','Benaceur'),
    ('55','002','بلدة اعمر','Blidet Amor','Blidet Amor'),
    ('55','003','العالية','El Alia','El Alia'),
    ('55','004','الحجيرة','El Hadjira','El Hadjira'),
    ('55','005','المنقر','M''Naguer','M''Naguer'),
    ('55','006','المقارين','Megarine','Megarine'),
    ('55','007','النزلة','Nezla','Nezla'),
    ('55','008','سيدي سليمان','Sidi Slimane','Sidi Slimane'),
    ('55','009','الطيبات','Taibet','Taibet'),
    ('55','010','تبسبست','Tebesbest','Tebesbest'),
    ('55','011','تماسين','Temacine','Temacine'),
    ('55','012','تقرت','Touggourt','Touggourt'),
    ('55','013','الزاوية العابدية','Zaouia El Abidia','Zaouia El Abidia'),
    ('56','001','برج الحواس','Bordj El Haouass','Bordj El Haouass'),
    ('56','002','جانت','Djanet','Djanet'),
    ('57','001','جامعة','Djamaa','Djamaa'),
    ('57','002','المغير','El-M''ghaier','El-M''ghaier'),
    ('57','003','المرارة','M''Rara','M''Rara'),
    ('57','004','أم الطيور','Oum Touyour','Oum Touyour'),
    ('57','005','سيدي عمران','Sidi Amrane','Sidi Amrane'),
    ('57','006','سيدي خليل','Sidi Khelil','Sidi Khelil'),
    ('57','007','سطيل','Still','Still'),
    ('57','008','تندلة','Tenedla','Tenedla'),
    ('58','001','المنيعة','El Meniaa','El Meniaa'),
    ('58','002','حاسي الفحل','Hassi Fehal','Hassi Fehal'),
    ('58','003','حاسي القارة','Hassi Gara','Hassi Gara')
)
INSERT INTO public.communes (wilaya_id, code, name, active)
SELECT w.id, s.wcode || '-' || s.seq, jsonb_build_object('ar', s.ar, 'fr', s.fr, 'en', s.en), true
FROM src s
JOIN public.wilayas w ON w.code = s.wcode
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name, active = true, updated_at = now();

COMMIT;
